
import { Word } from './types';
import { EXTENDED_VOCABULARY } from './vocabulary-extended';
import { VOCAB_201_300 } from './vocabulary-201-300';
import { VOCAB_301_400 } from './vocabulary-301-400';
import { VOCAB_401_500 } from './vocabulary-401-500';

// Categories for better filtering
export const CATEGORIES = [
  'All', 'Greetings', 'Time', 'Nature', 'People', 'Verbs', 'Adjectives', 'Objects', 'Numbers'
];

export const VOCABULARY_DATA: Word[] = [
  { id: 1, arabic: 'أنا', transliteration: 'ana', meaning: 'I / Me', category: 'People', mnemonic: 'ANA - I am Ana' },
  { id: 2, arabic: 'أنت', transliteration: 'anta', meaning: 'You (masculine)', category: 'People', mnemonic: 'ANTA - You are an ant-a' },
  { id: 3, arabic: 'مرحبا', transliteration: 'marhaba', meaning: 'Hello', category: 'Greetings', mnemonic: 'MAR-HABA - Hello, Mar has a habit' },
  { id: 4, arabic: 'شكرا', transliteration: 'syukran', meaning: 'Thank you', category: 'Greetings', mnemonic: 'SYUKRAN - Thank you for the sugar ran' },
  { id: 5, arabic: 'يأكل', transliteration: 'ya\'kul', meaning: 'To eat', category: 'Verbs', mnemonic: 'YA-KUL - Ya! Cool to eat' },
  { id: 6, arabic: 'يشرب', transliteration: 'yasyrab', meaning: 'To drink', category: 'Verbs', mnemonic: 'YASY-RAB - Yash rubs to drink' },
  { id: 7, arabic: 'ماء', transliteration: 'ma\'', meaning: 'Water', category: 'Nature', mnemonic: 'MAA - Ma needs water' },
  { id: 8, arabic: 'شمس', transliteration: 'syams', meaning: 'Sun', category: 'Nature', mnemonic: 'SYAMS - Shams in the sun' },
  { id: 9, arabic: 'قمر', transliteration: 'qamar', meaning: 'Moon', category: 'Time', mnemonic: 'QAMAR - Camera captures the moon' },
  { id: 10, arabic: 'اليوم', transliteration: 'al-yaum', meaning: 'Today', category: 'Time', mnemonic: 'AL-YAUM - All yawn today' },
  { id: 11, arabic: 'غدا', transliteration: 'ghadan', meaning: 'Tomorrow', category: 'Time', mnemonic: 'GHADAN - Got a den tomorrow' },
  { id: 12, arabic: 'أمس', transliteration: 'ams', meaning: 'Yesterday', category: 'Time', mnemonic: 'AMS - Amsterdam yesterday' },
  { id: 13, arabic: 'كبير', transliteration: 'kabir', meaning: 'Big', category: 'Adjectives', mnemonic: 'KABIR - Big cabin' },
  { id: 14, arabic: 'صغير', transliteration: 'saghir', meaning: 'Small', category: 'Adjectives', mnemonic: 'SAGHIR - Small sugar' },
  { id: 15, arabic: 'لذيذ', transliteration: 'laziz', meaning: 'Delicious', category: 'Adjectives', mnemonic: 'LAZIZ - Lad eats delicious dish' },
  { id: 16, arabic: 'قطة', transliteration: 'qittah', meaning: 'Cat', category: 'Nature', mnemonic: 'QITTAH - Quit the cat' },
  { id: 17, arabic: 'كلب', transliteration: 'kalb', meaning: 'Dog', category: 'Nature', mnemonic: 'KALB - Call the dog' },
  { id: 18, arabic: 'كتاب', transliteration: 'kitab', meaning: 'Book', category: 'Objects', mnemonic: 'KITAB - Keep the book' },
  { id: 19, arabic: 'سيارة', transliteration: 'sayyarah', meaning: 'Car', category: 'Objects', mnemonic: 'SAYYARAH - Say yara in the car' },
  { id: 20, arabic: 'عائلة', transliteration: 'a\'ilah', meaning: 'Family', category: 'People', mnemonic: 'A\'ILAH - I love family' },
  { id: 21, arabic: 'صديق', transliteration: 'sadiq', meaning: 'Friend', category: 'People', mnemonic: 'SADIQ - Sad? Seek a friend' },
  { id: 22, arabic: 'معلم', transliteration: 'mu\'allim', meaning: 'Teacher', category: 'People', mnemonic: 'MU\'ALLIM - My teacher is slim' },
  { id: 23, arabic: 'طالب', transliteration: 'talib', meaning: 'Student', category: 'People', mnemonic: 'TALIB - Tall student' },
  { id: 24, arabic: 'بلد', transliteration: 'balad', meaning: 'Country', category: 'Nature', mnemonic: 'BALAD - Ballad of a country' },
  { id: 25, arabic: 'لغة', transliteration: 'lughah', meaning: 'Language', category: 'Objects', mnemonic: 'LUGHAH - Luggage of language' },
  { id: 26, arabic: 'بيت', transliteration: 'bait', meaning: 'House / Home', category: 'Objects', mnemonic: 'BAIT - Bait at home' },
  { id: 27, arabic: 'مدرسة', transliteration: 'madrasah', meaning: 'School', category: 'Objects', mnemonic: 'MADRASAH - Mad at school' },
  { id: 28, arabic: 'حب', transliteration: 'hubb', meaning: 'Love', category: 'Greetings', mnemonic: 'HUBB - Hug with love' },
  { id: 29, arabic: 'سلام', transliteration: 'salam', meaning: 'Peace', category: 'Greetings', mnemonic: 'SALAM - Salami brings peace' },
  { id: 30, arabic: 'قلب', transliteration: 'qalb', meaning: 'Heart', category: 'People', mnemonic: 'QALB - Call the heart' },
  { id: 31, arabic: 'يذهب', transliteration: 'yazhab', meaning: 'To go', category: 'Verbs', mnemonic: 'YAZHAB - Yad has to go' },
  { id: 32, arabic: 'يأتي', transliteration: 'ya\'ti', meaning: 'To come', category: 'Verbs', mnemonic: 'YA\'TI - Yeti will come' },
  { id: 33, arabic: 'يرى', transliteration: 'yara', meaning: 'To see', category: 'Verbs', mnemonic: 'YARA - Yara can see' },
  { id: 34, arabic: 'يسمع', transliteration: 'yasma\'', meaning: 'To hear', category: 'Verbs', mnemonic: 'YASMA\' - Yes, ma, I hear' },
  { id: 35, arabic: 'يتكلم', transliteration: 'yatakallam', meaning: 'To speak', category: 'Verbs', mnemonic: 'YATAKALLAM - Yata calls to speak' },
  { id: 36, arabic: 'يقرأ', transliteration: 'yaqra\'', meaning: 'To read', category: 'Verbs', mnemonic: 'YAQRA\' - Yak reads' },
  { id: 37, arabic: 'يكتب', transliteration: 'yaktub', meaning: 'To write', category: 'Verbs', mnemonic: 'YAKTUB - Yak tubs to write' },
  { id: 38, arabic: 'يشتري', transliteration: 'yasytari', meaning: 'To buy', category: 'Verbs', mnemonic: 'YASYTARI - Yash tries to buy' },
  { id: 39, arabic: 'يبيع', transliteration: 'yabi\'', meaning: 'To sell', category: 'Verbs', mnemonic: 'YABI\' - Yabby sells' },
  { id: 40, arabic: 'يصنع', transliteration: 'yasna\'', meaning: 'To make', category: 'Verbs', mnemonic: 'YASNA\' - Yes, na makes it' },
  { id: 41, arabic: 'يستخدم', transliteration: 'yastakhdam', meaning: 'To use', category: 'Verbs', mnemonic: 'YASTAKHDAM - Yes, stack them to use' },
  { id: 42, arabic: 'يعرف', transliteration: 'ya\'rif', meaning: 'To know', category: 'Verbs', mnemonic: 'YA\'RIF - Yarif knows' },
  { id: 43, arabic: 'يفكر', transliteration: 'yufakkir', meaning: 'To think', category: 'Verbs', mnemonic: 'YUFAKKIR - You faker, think!' },
  { id: 44, arabic: 'يقول', transliteration: 'yaqul', meaning: 'To say', category: 'Verbs', mnemonic: 'YAQUL - Yak says cool' },
  { id: 45, arabic: 'يحمل', transliteration: 'yahmil', meaning: 'To hold / To carry', category: 'Verbs', mnemonic: 'YAHMIL - Yah, mill holds' },
  { id: 46, arabic: 'يقف', transliteration: 'yaqif', meaning: 'To stand', category: 'Verbs', mnemonic: 'YAQIF - Yak if you stand' },
  { id: 47, arabic: 'يجلس', transliteration: 'yajlis', meaning: 'To sit', category: 'Verbs', mnemonic: 'YAJLIS - Yaj lists while sitting' },
  { id: 48, arabic: 'ينام', transliteration: 'yanam', meaning: 'To sleep', category: 'Verbs', mnemonic: 'YANAM - Yawn and sleep' },
  { id: 49, arabic: 'يستيقظ', transliteration: 'yastayqiz', meaning: 'To wake up', category: 'Verbs', mnemonic: 'YASTAYQIZ - Yes, stay quiz to wake up' },
  { id: 50, arabic: 'يمشي', transliteration: 'yamsyi', meaning: 'To walk', category: 'Verbs', mnemonic: 'YAMSYI - Yam she walks' },
  { id: 51, arabic: 'يجري', transliteration: 'yajri', meaning: 'To run', category: 'Verbs', mnemonic: 'YAJRI - Yaj runs free' },
  { id: 52, arabic: 'يسبح', transliteration: 'yasbah', meaning: 'To swim', category: 'Verbs', mnemonic: 'YASBAH - Yes, bah! Swim!' },
  { id: 53, arabic: 'يطير', transliteration: 'yatir', meaning: 'To fly', category: 'Verbs', mnemonic: 'YATIR - Yeti flies' },
  { id: 54, arabic: 'يفتح', transliteration: 'yaftah', meaning: 'To open', category: 'Verbs', mnemonic: 'YAFTAH - Yaf opens the door' },
  { id: 55, arabic: 'يغلق', transliteration: 'yughliq', meaning: 'To close', category: 'Verbs', mnemonic: 'YUGHLIQ - You glue to close' },
  { id: 56, arabic: 'يدخل', transliteration: 'yadkhul', meaning: 'To enter', category: 'Verbs', mnemonic: 'YADKHUL - Yad calls to enter' },
  { id: 57, arabic: 'يخرج', transliteration: 'yakhruj', meaning: 'To exit', category: 'Verbs', mnemonic: 'YAKHRUJ - Yak rushes to exit' },
  { id: 58, arabic: 'يلتقي', transliteration: 'yaltaqi', meaning: 'To meet', category: 'Verbs', mnemonic: 'YALTAQI - Yalta key to meet' },
  { id: 59, arabic: 'ينتظر', transliteration: 'yantazir', meaning: 'To wait', category: 'Verbs', mnemonic: 'YANTAZIR - Yanta zips to wait' },
  { id: 60, arabic: 'يعود', transliteration: 'ya\'ud', meaning: 'To return', category: 'Verbs', mnemonic: 'YA\'UD - You\'d return' },
  { id: 61, arabic: 'واحد', transliteration: 'wahid', meaning: 'One', category: 'Numbers', mnemonic: 'WAHID - One wah kid' },
  { id: 62, arabic: 'اثنان', transliteration: 'ithnan', meaning: 'Two', category: 'Numbers', mnemonic: 'ITHNAN - It\'s nan, two!' },
  { id: 63, arabic: 'ثلاثة', transliteration: 'thalathah', meaning: 'Three', category: 'Numbers', mnemonic: 'THALATHAH - Three lathers' },
  { id: 64, arabic: 'أربعة', transliteration: 'arba\'ah', meaning: 'Four', category: 'Numbers', mnemonic: 'ARBA\'AH - Four are baa' },
  { id: 65, arabic: 'خمسة', transliteration: 'khamsah', meaning: 'Five', category: 'Numbers', mnemonic: 'KHAMSAH - Five hams' },
  { id: 66, arabic: 'ستة', transliteration: 'sittah', meaning: 'Six', category: 'Numbers', mnemonic: 'SITTAH - Six sitters' },
  { id: 67, arabic: 'سبعة', transliteration: 'sab\'ah', meaning: 'Seven', category: 'Numbers', mnemonic: 'SAB\'AH - Seven sabers' },
  { id: 68, arabic: 'ثمانية', transliteration: 'thamaniyah', meaning: 'Eight', category: 'Numbers', mnemonic: 'THAMANIYAH - Eight the mania' },
  { id: 69, arabic: 'تسعة', transliteration: 'tis\'ah', meaning: 'Nine', category: 'Numbers', mnemonic: 'TIS\'AH - Nine teas' },
  { id: 70, arabic: 'عشرة', transliteration: 'asyarah', meaning: 'Ten', category: 'Numbers', mnemonic: 'ASYARAH - Ten ash are' },
  { id: 71, arabic: 'مئة', transliteration: 'mi\'ah', meaning: 'Hundred', category: 'Numbers', mnemonic: 'MI\'AH - Mia has hundred' },
  { id: 72, arabic: 'ألف', transliteration: 'alf', meaning: 'Thousand', category: 'Numbers', mnemonic: 'ALF - Alf has thousand' },
  { id: 73, arabic: 'أحمر', transliteration: 'ahmar', meaning: 'Red', category: 'Adjectives', mnemonic: 'AHMAR - Ah! Red hammer' },
  { id: 74, arabic: 'أزرق', transliteration: 'azraq', meaning: 'Blue', category: 'Adjectives', mnemonic: 'AZRAQ - Azure blue rack' },
  { id: 75, arabic: 'أبيض', transliteration: 'abyad', meaning: 'White', category: 'Adjectives', mnemonic: 'ABYAD - A bee ad is white' },
  { id: 76, arabic: 'أسود', transliteration: 'aswad', meaning: 'Black', category: 'Adjectives', mnemonic: 'ASWAD - A swad is black' },
  { id: 77, arabic: 'جديد', transliteration: 'jadid', meaning: 'New', category: 'Adjectives', mnemonic: 'JADID - Jaded? Get new!' },
  { id: 78, arabic: 'قديم', transliteration: 'qadim', meaning: 'Old', category: 'Adjectives', mnemonic: 'QADIM - Cadillac is old' },
  { id: 79, arabic: 'جيد', transliteration: 'jayyid', meaning: 'Good', category: 'Adjectives', mnemonic: 'JAYYID - Jay is good' },
  { id: 80, arabic: 'سيء', transliteration: 'sayyi\'', meaning: 'Bad', category: 'Adjectives', mnemonic: 'SAYYI\' - Say yee, it\'s bad' },
  { id: 81, arabic: 'عالي', transliteration: '\'ali', meaning: 'High', category: 'Adjectives', mnemonic: '\'ALI - Ali is high' },
  { id: 82, arabic: 'رخيص', transliteration: 'rakhis', meaning: 'Cheap', category: 'Adjectives', mnemonic: 'RAKHIS - Rack is cheap' },
  { id: 83, arabic: 'طويل', transliteration: 'tawil', meaning: 'Long / Tall', category: 'Adjectives', mnemonic: 'TAWIL - Towel is long' },
  { id: 84, arabic: 'قصير', transliteration: 'qasir', meaning: 'Short', category: 'Adjectives', mnemonic: 'QASIR - Casser is short' },
  { id: 85, arabic: 'كثير', transliteration: 'kathir', meaning: 'Many / Much', category: 'Adjectives', mnemonic: 'KATHIR - Cat has many' },
  { id: 86, arabic: 'قليل', transliteration: 'qalil', meaning: 'Few / Little', category: 'Adjectives', mnemonic: 'QALIL - Cali has few' },
  { id: 87, arabic: 'حار', transliteration: 'harr', meaning: 'Hot', category: 'Adjectives', mnemonic: 'HARR - Hard when hot' },
  { id: 88, arabic: 'بارد', transliteration: 'barid', meaning: 'Cold', category: 'Adjectives', mnemonic: 'BARID - Buried in cold' },
  { id: 89, arabic: 'دافئ', transliteration: 'dafi\'', meaning: 'Warm', category: 'Adjectives', mnemonic: 'DAFI\' - Daffy is warm' },
  { id: 90, arabic: 'بارد', transliteration: 'barid', meaning: 'Cool', category: 'Adjectives', mnemonic: 'BARID - Barrel is cool' },
  { id: 91, arabic: 'صعب', transliteration: 'sa\'b', meaning: 'Difficult', category: 'Adjectives', mnemonic: 'SA\'B - Sab is difficult' },
  { id: 92, arabic: 'سهل', transliteration: 'sahl', meaning: 'Easy', category: 'Adjectives', mnemonic: 'SAHL - Sail is easy' },
  { id: 93, arabic: 'ممتع', transliteration: 'mumti\'', meaning: 'Fun / Enjoyable', category: 'Adjectives', mnemonic: 'MUMTI\' - Mummy is fun' },
  { id: 94, arabic: 'سعيد', transliteration: 'sa\'id', meaning: 'Happy', category: 'Adjectives', mnemonic: 'SA\'ID - Said is happy' },
  { id: 95, arabic: 'حزين', transliteration: 'hazin', meaning: 'Sad', category: 'Adjectives', mnemonic: 'HAZIN - Hazing makes sad' },
  { id: 96, arabic: 'مخيف', transliteration: 'mukhif', meaning: 'Scary', category: 'Adjectives', mnemonic: 'MUKHIF - Muck if scary' },
  { id: 97, arabic: 'قوي', transliteration: 'qawi', meaning: 'Strong', category: 'Adjectives', mnemonic: 'QAWI - Kiwi is strong' },
  { id: 98, arabic: 'ضعيف', transliteration: 'daif', meaning: 'Weak', category: 'Adjectives', mnemonic: 'DAIF - Deaf is weak' },
  { id: 99, arabic: 'سريع', transliteration: 'sari', meaning: 'Fast', category: 'Adjectives', mnemonic: 'SARI - Sorry, too fast!' },
  { id: 100, arabic: 'بطيء', transliteration: 'bati', meaning: 'Slow', category: 'Adjectives', mnemonic: 'BATI - Batty is slow' },
];

export const TOTAL_VOCAB = [
  ...VOCABULARY_DATA,
  ...EXTENDED_VOCABULARY,
  ...VOCAB_201_300,
  ...VOCAB_301_400,
  ...VOCAB_401_500
];
