import { Word } from './types';

export const VOCAB_201_300: Word[] = [
  { id: 201, arabic: 'يكسر', transliteration: 'yaksir', meaning: 'To break', category: 'Verbs', mnemonic: 'YAKSIR - Yak sir breaks' },
  { id: 202, arabic: 'يسقط', transliteration: 'yasqut', meaning: 'To fall', category: 'Verbs', mnemonic: 'YASQUT - Yes, cut falls' },
  { id: 203, arabic: 'يرفع', transliteration: 'yarfa\'', meaning: 'To raise', category: 'Verbs', mnemonic: 'YARFA\' - Yar fa raises' },
  { id: 204, arabic: 'يخفض', transliteration: 'yakhfid', meaning: 'To lower', category: 'Verbs', mnemonic: 'YAKHFID - Yak fid lowers' },
  { id: 205, arabic: 'يدفع', transliteration: 'yadfa\'', meaning: 'To push', category: 'Verbs', mnemonic: 'YADFA\' - Yad fa pushes' },
  { id: 206, arabic: 'يسحب', transliteration: 'yashab', meaning: 'To pull', category: 'Verbs', mnemonic: 'YASHAB - Yash ab pulls' },
  { id: 207, arabic: 'يرمي', transliteration: 'yarmi', meaning: 'To throw', category: 'Verbs', mnemonic: 'YARMI - Yar me throws' },
  { id: 208, arabic: 'يأخذ', transliteration: 'ya\'khuz', meaning: 'To take', category: 'Verbs', mnemonic: 'YA\'KHUZ - Yak hood takes' },
  { id: 209, arabic: 'يضع', transliteration: 'yada\'', meaning: 'To put', category: 'Verbs', mnemonic: 'YADA\' - Yada puts' },
  { id: 210, arabic: 'يصف', transliteration: 'yasif', meaning: 'To line up', category: 'Verbs', mnemonic: 'YASIF - Yes, if lines up' },
  { id: 211, arabic: 'يجمع', transliteration: 'yajma\'', meaning: 'To collect', category: 'Verbs', mnemonic: 'YAJMA\' - Yaj ma collects' },
  { id: 212, arabic: 'يقسم', transliteration: 'yaqsim', meaning: 'To divide', category: 'Verbs', mnemonic: 'YAQSIM - Yak sim divides' },
  { id: 213, arabic: 'يخلط', transliteration: 'yakhlut', meaning: 'To mix', category: 'Verbs', mnemonic: 'YAKHLUT - Yak loot mixes' },
  { id: 214, arabic: 'يزيد', transliteration: 'yazid', meaning: 'To increase', category: 'Verbs', mnemonic: 'YAZID - Yazid increases' },
  { id: 215, arabic: 'ينقص', transliteration: 'yanqus', meaning: 'To decrease', category: 'Verbs', mnemonic: 'YANQUS - Yan cuss decreases' },
  { id: 216, arabic: 'يستمر', transliteration: 'yastamirr', meaning: 'To continue', category: 'Verbs', mnemonic: 'YASTAMIRR - Yes, tam continues' },
  { id: 217, arabic: 'يتوقف', transliteration: 'yatawaqqaf', meaning: 'To stop', category: 'Verbs', mnemonic: 'YATAWAQQAF - Yata wok stops' },
  { id: 218, arabic: 'يتحرك', transliteration: 'yataharrak', meaning: 'To move', category: 'Verbs', mnemonic: 'YATAHARRAK - Yata rack moves' },
  { id: 219, arabic: 'يدور', transliteration: 'yadur', meaning: 'To turn', category: 'Verbs', mnemonic: 'YADUR - Yad door turns' },
  { id: 220, arabic: 'ينحني', transliteration: 'yanhani', meaning: 'To bend', category: 'Verbs', mnemonic: 'YANHANI - Yan honey bends' },
  { id: 221, arabic: 'يعبر', transliteration: 'ya\'bur', meaning: 'To cross', category: 'Verbs', mnemonic: 'YA\'BUR - Yabber crosses' },
  { id: 222, arabic: 'يمر', transliteration: 'yamurr', meaning: 'To pass', category: 'Verbs', mnemonic: 'YAMURR - Yam more passes' },
  { id: 223, arabic: 'يركب', transliteration: 'yarkab', meaning: 'To ride', category: 'Verbs', mnemonic: 'YARKAB - Yar cab rides' },
  { id: 224, arabic: 'ينزل', transliteration: 'yanzil', meaning: 'To get off', category: 'Verbs', mnemonic: 'YANZIL - Yan zeal gets off' },
  { id: 225, arabic: 'يقود', transliteration: 'yaqud', meaning: 'To drive', category: 'Verbs', mnemonic: 'YAQUD - Yak could drive' },
  { id: 226, arabic: 'يوقف', transliteration: 'yuqif', meaning: 'To stop something', category: 'Verbs', mnemonic: 'YUQIF - You kif stops' },
  { id: 227, arabic: 'يسرع', transliteration: 'yusri\'', meaning: 'To hurry', category: 'Verbs', mnemonic: 'YUSRI\' - You sri hurries' },
  { id: 228, arabic: 'يتأخر', transliteration: 'yata\'akhkhar', meaning: 'To be late', category: 'Verbs', mnemonic: 'YATA\'AKHKHAR - Yata car is late' },
  { id: 229, arabic: 'يلحق', transliteration: 'yalhaq', meaning: 'To catch up', category: 'Verbs', mnemonic: 'YALHAQ - Yal hack catches up' },
  { id: 230, arabic: 'وعد', transliteration: 'wa\'d', meaning: 'Promise', category: 'Verbs', mnemonic: 'WA\'D - Wad is a promise' },
  { id: 231, arabic: 'يطلب', transliteration: 'yatlub', meaning: 'To request', category: 'Verbs', mnemonic: 'YATLUB - Yat lub requests' },
  { id: 232, arabic: 'يساعد', transliteration: 'yusa\'id', meaning: 'To help', category: 'Verbs', mnemonic: 'YUSA\'ID - You said helps' },
  { id: 233, arabic: 'يتعب', transliteration: 'yat\'ab', meaning: 'To be tired', category: 'Verbs', mnemonic: 'YAT\'AB - Yat tab is tired' },
  { id: 234, arabic: 'يفرح', transliteration: 'yafrah', meaning: 'To be glad', category: 'Verbs', mnemonic: 'YAFRAH - Yaf rah is glad' },
  { id: 235, arabic: 'يغضب', transliteration: 'yaghdab', meaning: 'To be angry', category: 'Verbs', mnemonic: 'YAGHDAB - Yag dab is angry' },
  { id: 236, arabic: 'يتفاجأ', transliteration: 'yatafaja\'', meaning: 'To be surprised', category: 'Verbs', mnemonic: 'YATAFAJA\' - Yata faja surprised' },
  { id: 237, arabic: 'قلق', transliteration: 'qalaq', meaning: 'Worry', category: 'Adjectives', mnemonic: 'QALAQ - Caw lack worry' },
  { id: 238, arabic: 'راحة', transliteration: 'rahah', meaning: 'Relief', category: 'Adjectives', mnemonic: 'RAHAH - Raha is relief' },
  { id: 239, arabic: 'مؤسف', transliteration: 'mu\'sif', meaning: 'Regrettable', category: 'Adjectives', mnemonic: 'MU\'SIF - Muse if regrettable' },
  { id: 240, arabic: 'مهم', transliteration: 'muhimm', meaning: 'Important', category: 'Adjectives', mnemonic: 'MUHIMM - Moo him important' },
  { id: 241, arabic: 'مريح', transliteration: 'murih', meaning: 'Convenient', category: 'Adjectives', mnemonic: 'MURIH - More convenient' },
  { id: 242, arabic: 'غير مريح', transliteration: 'ghair murih', meaning: 'Inconvenient', category: 'Adjectives', mnemonic: 'GHAIR MURIH - Gear more inconvenient' },
  { id: 243, arabic: 'بسيط', transliteration: 'basit', meaning: 'Simple', category: 'Adjectives', mnemonic: 'BASIT - Basket simple' },
  { id: 244, arabic: 'معقد', transliteration: 'mu\'aqqad', meaning: 'Complicated', category: 'Adjectives', mnemonic: 'MU\'AQQAD - Moo quad complicated' },
  { id: 245, arabic: 'هادئ', transliteration: 'hadi\'', meaning: 'Quiet', category: 'Adjectives', mnemonic: 'HADI\' - Hadi is quiet' },
  { id: 246, arabic: 'صاخب', transliteration: 'sakhib', meaning: 'Noisy', category: 'Adjectives', mnemonic: 'SAKHIB - Sack hib noisy' },
  { id: 247, arabic: 'جميل', transliteration: 'jamil', meaning: 'Beautiful', category: 'Adjectives', mnemonic: 'JAMIL - Jamil is beautiful' },
  { id: 248, arabic: 'قذر', transliteration: 'qazir', meaning: 'Dirty', category: 'Adjectives', mnemonic: 'QAZIR - Cad here dirty' },
  { id: 249, arabic: 'مشهور', transliteration: 'masyhur', meaning: 'Famous', category: 'Adjectives', mnemonic: 'MASYHUR - Mash her famous' },
  { id: 250, arabic: 'خاص', transliteration: 'khass', meaning: 'Special', category: 'Adjectives', mnemonic: 'KHASS - Has special' },
  { id: 251, arabic: 'عادي', transliteration: '\'adi', meaning: 'Normal', category: 'Adjectives', mnemonic: '\'ADI - Addy is normal' },
  { id: 252, arabic: 'نفس', transliteration: 'nafs', meaning: 'Same', category: 'Adjectives', mnemonic: 'NAFS - Naps same' },
  { id: 253, arabic: 'مختلف', transliteration: 'mukhtalif', meaning: 'Different', category: 'Adjectives', mnemonic: 'MUKHTALIF - Muck tall different' },
  { id: 254, arabic: 'صحيح', transliteration: 'sahih', meaning: 'Correct', category: 'Adjectives', mnemonic: 'SAHIH - Sah he correct' },
  { id: 255, arabic: 'خطأ', transliteration: 'khata\'', meaning: 'Mistake', category: 'Adjectives', mnemonic: 'KHATA\' - Cat a mistake' },
  { id: 256, arabic: 'خطير', transliteration: 'khatir', meaning: 'Dangerous', category: 'Adjectives', mnemonic: 'KHATIR - Cat ear dangerous' },
  { id: 257, arabic: 'آمن', transliteration: 'amin', meaning: 'Safe', category: 'Adjectives', mnemonic: 'AMIN - Amen safe' },
  { id: 258, arabic: 'نشيط', transliteration: 'nasyit', meaning: 'Energetic', category: 'Adjectives', mnemonic: 'NASYIT - Nash it energetic' },
  { id: 259, arabic: 'مريض', transliteration: 'marid', meaning: 'Sick', category: 'Adjectives', mnemonic: 'MARID - Mar id sick' },
  { id: 260, arabic: 'مؤلم', transliteration: 'mu\'lim', meaning: 'Painful', category: 'Adjectives', mnemonic: 'MU\'LIM - Moo limb painful' },
  { id: 261, arabic: 'سميك', transliteration: 'samik', meaning: 'Thick', category: 'Adjectives', mnemonic: 'SAMIK - Same thick' },
  { id: 262, arabic: 'رفيع', transliteration: 'rafi\'', meaning: 'Thin', category: 'Adjectives', mnemonic: 'RAFI\' - Raffy thin' },
  { id: 263, arabic: 'واسع', transliteration: 'wasi\'', meaning: 'Wide', category: 'Adjectives', mnemonic: 'WASI\' - Was he wide' },
  { id: 264, arabic: 'ضيق', transliteration: 'dayyiq', meaning: 'Narrow', category: 'Adjectives', mnemonic: 'DAYYIQ - Day ick narrow' },
  { id: 265, arabic: 'عميق', transliteration: '\'amiq', meaning: 'Deep', category: 'Adjectives', mnemonic: '\'AMIQ - Am ick deep' },
  { id: 266, arabic: 'ضحل', transliteration: 'dahl', meaning: 'Shallow', category: 'Adjectives', mnemonic: 'DAHL - Doll shallow' },
  { id: 267, arabic: 'ثقيل', transliteration: 'thaqil', meaning: 'Heavy', category: 'Adjectives', mnemonic: 'THAQIL - Tack ill heavy' },
  { id: 268, arabic: 'خفيف', transliteration: 'khafif', meaning: 'Light', category: 'Adjectives', mnemonic: 'KHAFIF - Calf if light' },
  { id: 269, arabic: 'صلب', transliteration: 'salb', meaning: 'Hard', category: 'Adjectives', mnemonic: 'SALB - Salb hard' },
  { id: 270, arabic: 'ناعم', transliteration: 'na\'im', meaning: 'Soft', category: 'Adjectives', mnemonic: 'NA\'IM - Name soft' },
  { id: 271, arabic: 'مستدير', transliteration: 'mustadir', meaning: 'Round', category: 'Adjectives', mnemonic: 'MUSTADIR - Must a deer round' },
  { id: 272, arabic: 'مربع', transliteration: 'murabba\'', meaning: 'Square', category: 'Adjectives', mnemonic: 'MURABBA\' - Moo rab square' },
  { id: 273, arabic: 'مسطح', transliteration: 'musattah', meaning: 'Flat', category: 'Adjectives', mnemonic: 'MUSATTAH - Moo sat flat' },
  { id: 274, arabic: 'مستقيم', transliteration: 'mustaqim', meaning: 'Straight', category: 'Adjectives', mnemonic: 'MUSTAQIM - Must a kim straight' },
  { id: 275, arabic: 'قريب', transliteration: 'qarib', meaning: 'Near', category: 'Adjectives', mnemonic: 'QARIB - Car rib near' },
  { id: 276, arabic: 'بعيد', transliteration: 'ba\'id', meaning: 'Far', category: 'Adjectives', mnemonic: 'BA\'ID - Bade far' },
  { id: 277, arabic: 'شاب', transliteration: 'syabb', meaning: 'Young', category: 'Adjectives', mnemonic: 'SYABB - Shab young' },
  { id: 278, arabic: 'عجوز', transliteration: '\'ajuz', meaning: 'Old', category: 'Adjectives', mnemonic: '\'AJUZ - Ah juice old' },
  { id: 279, arabic: 'مشرق', transliteration: 'musyriq', meaning: 'Bright', category: 'Adjectives', mnemonic: 'MUSYRIQ - Mush rick bright' },
  { id: 280, arabic: 'مظلم', transliteration: 'muzlim', meaning: 'Dark', category: 'Adjectives', mnemonic: 'MUZLIM - Muzz limb dark' },
  { id: 281, arabic: 'كثيف', transliteration: 'kathif', meaning: 'Thick', category: 'Adjectives', mnemonic: 'KATHIF - Cat if thick' },
  { id: 282, arabic: 'خفيف', transliteration: 'khafif', meaning: 'Thin', category: 'Adjectives', mnemonic: 'KHAFIF - Calf if thin' },
  { id: 283, arabic: 'حلو', transliteration: 'hilw', meaning: 'Sweet', category: 'Adjectives', mnemonic: 'HILW - Hill sweet' },
  { id: 284, arabic: 'حار', transliteration: 'harr', meaning: 'Spicy', category: 'Adjectives', mnemonic: 'HARR - Har spicy' },
  { id: 285, arabic: 'مر', transliteration: 'murr', meaning: 'Bitter', category: 'Adjectives', mnemonic: 'MURR - Murr bitter' },
  { id: 286, arabic: 'حامض', transliteration: 'hamid', meaning: 'Sour', category: 'Adjectives', mnemonic: 'HAMID - Ham id sour' },
  { id: 287, arabic: 'مالح', transliteration: 'malih', meaning: 'Salty', category: 'Adjectives', mnemonic: 'MALIH - Mall he salty' },
  { id: 288, arabic: 'عطر', transliteration: '\'itr', meaning: 'Fragrant', category: 'Adjectives', mnemonic: '\'ITR - It are fragrant' },
  { id: 289, arabic: 'كريه', transliteration: 'karih', meaning: 'Smelly', category: 'Adjectives', mnemonic: 'KARIH - Car he smelly' },
  { id: 290, arabic: 'رائحة طيبة', transliteration: 'raihah tayyibah', meaning: 'Good smell', category: 'Adjectives', mnemonic: 'RAIHAH TAYYIBAH - Ray ha good smell' },
  { id: 291, arabic: 'مزعج', transliteration: 'muzi\'', meaning: 'Annoying', category: 'Adjectives', mnemonic: 'MUZI\' - Moo zij annoying' },
  { id: 292, arabic: 'ذكي', transliteration: 'zaki', meaning: 'Smart', category: 'Adjectives', mnemonic: 'ZAKI - Ducky smart' },
  { id: 293, arabic: 'غبي', transliteration: 'ghabi', meaning: 'Stupid', category: 'Adjectives', mnemonic: 'GHABI - Gabby stupid' },
  { id: 294, arabic: 'لطيف', transliteration: 'latif', meaning: 'Kind', category: 'Adjectives', mnemonic: 'LATIF - Lat if kind' },
  { id: 295, arabic: 'صارم', transliteration: 'sarim', meaning: 'Strict', category: 'Adjectives', mnemonic: 'SARIM - Sari m strict' },
  { id: 296, arabic: 'مشغول', transliteration: 'masyghul', meaning: 'Busy', category: 'Adjectives', mnemonic: 'MASYGHUL - Mash ghoul busy' },
  { id: 297, arabic: 'فراغ', transliteration: 'faragh', meaning: 'Free time', category: 'Adjectives', mnemonic: 'FARAGH - Far rag free time' },
  { id: 298, arabic: 'ممتع', transliteration: 'mumti\'', meaning: 'Interesting', category: 'Adjectives', mnemonic: 'MUMTI\' - Mum tea interesting' },
  { id: 299, arabic: 'ممل', transliteration: 'mumill', meaning: 'Boring', category: 'Adjectives', mnemonic: 'MUMILL - Moo mill boring' },
  { id: 300, arabic: 'رائع', transliteration: 'ra\'i\'', meaning: 'Wonderful', category: 'Adjectives', mnemonic: 'RA\'I\' - Ray wonderful' },
];
