import { Word } from './types';

export const VOCAB_401_500: Word[] = [
  { id: 401, arabic: 'بريد إلكتروني', transliteration: 'barid iliktruniy', meaning: 'Email', category: 'Objects', mnemonic: 'BARID ILIKTRUNIY - Bar id electronic email' },
  { id: 402, arabic: 'إنترنت', transliteration: 'internet', meaning: 'Internet', category: 'Objects', mnemonic: 'INTERNET - Internet same' },
  { id: 403, arabic: 'هاتف محمول', transliteration: 'hatif mahmul', meaning: 'Mobile phone', category: 'Objects', mnemonic: 'HATIF MAHMUL - Hat if mobile' },
  { id: 404, arabic: 'هاتف ذكي', transliteration: 'hatif dhaki', meaning: 'Smartphone', category: 'Objects', mnemonic: 'HATIF DHAKI - Hat if smart' },
  { id: 405, arabic: 'رأس', transliteration: 'ras', meaning: 'Head', category: 'People', mnemonic: 'RAS - Rass head' },
  { id: 406, arabic: 'وجه', transliteration: 'wajh', meaning: 'Face', category: 'People', mnemonic: 'WAJH - Waj face' },
  { id: 407, arabic: 'عين', transliteration: 'ayn', meaning: 'Eye', category: 'People', mnemonic: 'AYN - I an eye' },
  { id: 408, arabic: 'أذن', transliteration: 'udhn', meaning: 'Ear', category: 'People', mnemonic: 'UDHN - Ud an ear' },
  { id: 409, arabic: 'أنف', transliteration: 'anf', meaning: 'Nose', category: 'People', mnemonic: 'ANF - An if nose' },
  { id: 410, arabic: 'فم', transliteration: 'fam', meaning: 'Mouth', category: 'People', mnemonic: 'FAM - Fam mouth' },
  { id: 411, arabic: 'سن', transliteration: 'sinn', meaning: 'Tooth', category: 'People', mnemonic: 'SINN - Sin tooth' },
  { id: 412, arabic: 'لسان', transliteration: 'lisan', meaning: 'Tongue', category: 'People', mnemonic: 'LISAN - Lease an tongue' },
  { id: 413, arabic: 'رقبة', transliteration: 'raqaba', meaning: 'Neck', category: 'People', mnemonic: 'RAQABA - Rack aba neck' },
  { id: 414, arabic: 'كتف', transliteration: 'katif', meaning: 'Shoulder', category: 'People', mnemonic: 'KATIF - Cat if shoulder' },
  { id: 415, arabic: 'ذراع', transliteration: 'dhira', meaning: 'Arm', category: 'People', mnemonic: 'DHIRA - Dear a arm' },
  { id: 416, arabic: 'يد', transliteration: 'yad', meaning: 'Hand', category: 'People', mnemonic: 'YAD - Yad hand' },
  { id: 417, arabic: 'إصبع', transliteration: 'isba', meaning: 'Finger', category: 'People', mnemonic: 'ISBA - Is ba finger' },
  { id: 418, arabic: 'ظفر', transliteration: 'zufr', meaning: 'Nail', category: 'People', mnemonic: 'ZUFR - Zoo fur nail' },
  { id: 419, arabic: 'صدر', transliteration: 'sadr', meaning: 'Chest', category: 'People', mnemonic: 'SADR - Sad are chest' },
  { id: 420, arabic: 'بطن', transliteration: 'batn', meaning: 'Stomach', category: 'People', mnemonic: 'BATN - Bat an stomach' },
  { id: 421, arabic: 'ظهر', transliteration: 'zahr', meaning: 'Back', category: 'People', mnemonic: 'ZAHR - Zar back' },
  { id: 422, arabic: 'خصر', transliteration: 'khasr', meaning: 'Waist', category: 'People', mnemonic: 'KHASR - Has are waist' },
  { id: 423, arabic: 'رجل', transliteration: 'rijl', meaning: 'Leg', category: 'People', mnemonic: 'RIJL - Rig l leg' },
  { id: 424, arabic: 'ركبة', transliteration: 'rukba', meaning: 'Knee', category: 'People', mnemonic: 'RUKBA - Rook ba knee' },
  { id: 425, arabic: 'دم', transliteration: 'dam', meaning: 'Blood', category: 'People', mnemonic: 'DAM - Dam blood' },
  { id: 426, arabic: 'عظم', transliteration: 'azm', meaning: 'Bone', category: 'People', mnemonic: 'AZM - As m bone' },
  { id: 427, arabic: 'جلد', transliteration: 'jild', meaning: 'Skin', category: 'People', mnemonic: 'JILD - Jill d skin' },
  { id: 428, arabic: 'شعر', transliteration: 'shaar', meaning: 'Hair', category: 'People', mnemonic: 'SHAAR - Share hair' },
  { id: 429, arabic: 'صوت', transliteration: 'sawt', meaning: 'Voice', category: 'People', mnemonic: 'SAWT - Sought voice' },
  { id: 430, arabic: 'صوت', transliteration: 'sawt', meaning: 'Sound', category: 'Objects', mnemonic: 'SAWT - Sought sound' },
  { id: 431, arabic: 'رائحة', transliteration: 'raiha', meaning: 'Smell', category: 'Objects', mnemonic: 'RAIHA - Ray ha smell' },
  { id: 432, arabic: 'طعم', transliteration: 'tam', meaning: 'Taste', category: 'Objects', mnemonic: 'TAM - Tam taste' },
  { id: 433, arabic: 'شعور', transliteration: 'shuur', meaning: 'Feeling', category: 'People', mnemonic: 'SHUUR - Sure feeling' },
  { id: 434, arabic: 'مزاج', transliteration: 'mizaj', meaning: 'Mood', category: 'People', mnemonic: 'MIZAJ - Miz aj mood' },
  { id: 435, arabic: 'حلم', transliteration: 'hulm', meaning: 'Dream', category: 'People', mnemonic: 'HULM - Helm dream' },
  { id: 436, arabic: 'أمل', transliteration: 'amal', meaning: 'Hope', category: 'People', mnemonic: 'AMAL - A mall hope' },
  { id: 437, arabic: 'سعادة', transliteration: 'saada', meaning: 'Happiness', category: 'People', mnemonic: 'SAADA - Sad a happiness' },
  { id: 438, arabic: 'تعاسة', transliteration: 'taasa', meaning: 'Misfortune', category: 'People', mnemonic: 'TAASA - Toss a misfortune' },
  { id: 439, arabic: 'نجاح', transliteration: 'najah', meaning: 'Success', category: 'Verbs', mnemonic: 'NAJAH - Naj ah success' },
  { id: 440, arabic: 'فشل', transliteration: 'fashal', meaning: 'Failure', category: 'Verbs', mnemonic: 'FASHAL - Fash al failure' },
  { id: 441, arabic: 'جهد', transliteration: 'juhd', meaning: 'Effort', category: 'Verbs', mnemonic: 'JUHD - Jude effort' },
  { id: 442, arabic: 'خبرة', transliteration: 'khibra', meaning: 'Experience', category: 'Verbs', mnemonic: 'KHIBRA - Kib ra experience' },
  { id: 443, arabic: 'معرفة', transliteration: 'marifa', meaning: 'Knowledge', category: 'Verbs', mnemonic: 'MARIFA - Mar ifa knowledge' },
  { id: 444, arabic: 'تقنية', transliteration: 'tiqniya', meaning: 'Technology', category: 'Verbs', mnemonic: 'TIQNIYA - Tick niya technology' },
  { id: 445, arabic: 'علم', transliteration: 'ilm', meaning: 'Science', category: 'Objects', mnemonic: 'ILM - Ill m science' },
  { id: 446, arabic: 'تاريخ', transliteration: 'tarikh', meaning: 'History', category: 'Objects', mnemonic: 'TARIKH - Tar ick history' },
  { id: 447, arabic: 'ثقافة', transliteration: 'thaqafa', meaning: 'Culture', category: 'Objects', mnemonic: 'THAQAFA - Tack afa culture' },
  { id: 448, arabic: 'تقليد', transliteration: 'taqlid', meaning: 'Tradition', category: 'Objects', mnemonic: 'TAQLID - Tack lid tradition' },
  { id: 449, arabic: 'عادة', transliteration: 'ada', meaning: 'Habit', category: 'Objects', mnemonic: 'ADA - Add a habit' },
  { id: 450, arabic: 'قاعدة', transliteration: 'qaida', meaning: 'Rule', category: 'Objects', mnemonic: 'QAIDA - Caid a rule' },
  { id: 451, arabic: 'قانون', transliteration: 'qanun', meaning: 'Law', category: 'Objects', mnemonic: 'QANUN - Can noon law' },
  { id: 452, arabic: 'حق', transliteration: 'haqq', meaning: 'Right', category: 'Objects', mnemonic: 'HAQQ - Hack right' },
  { id: 453, arabic: 'واجب', transliteration: 'wajib', meaning: 'Duty', category: 'Objects', mnemonic: 'WAJIB - Waj ib duty' },
  { id: 454, arabic: 'مسؤولية', transliteration: 'masuliya', meaning: 'Responsibility', category: 'Objects', mnemonic: 'MASULIYA - Mass ool responsibility' },
  { id: 455, arabic: 'حرية', transliteration: 'hurriya', meaning: 'Freedom', category: 'Objects', mnemonic: 'HURRIYA - Hurry ya freedom' },
  { id: 456, arabic: 'مساواة', transliteration: 'musawa', meaning: 'Equality', category: 'Objects', mnemonic: 'MUSAWA - Moo saw equality' },
  { id: 457, arabic: 'عدالة', transliteration: 'adala', meaning: 'Justice', category: 'Objects', mnemonic: 'ADALA - Add ala justice' },
  { id: 458, arabic: 'حقيقة', transliteration: 'haqiqa', meaning: 'Truth', category: 'Objects', mnemonic: 'HAQIQA - Hack ika truth' },
  { id: 459, arabic: 'كذب', transliteration: 'kadhib', meaning: 'Lie', category: 'Objects', mnemonic: 'KADHIB - Cad hib lie' },
  { id: 460, arabic: 'سر', transliteration: 'sirr', meaning: 'Secret', category: 'Objects', mnemonic: 'SIRR - Sir secret' },
  { id: 461, arabic: 'مشكلة', transliteration: 'mushkila', meaning: 'Problem', category: 'Objects', mnemonic: 'MUSHKILA - Mush kill a problem' },
  { id: 462, arabic: 'جواب', transliteration: 'jawab', meaning: 'Answer', category: 'Objects', mnemonic: 'JAWAB - Jaw ab answer' },
  { id: 463, arabic: 'سؤال', transliteration: 'sual', meaning: 'Question', category: 'Objects', mnemonic: 'SUAL - Sue al question' },
  { id: 464, arabic: 'شرح', transliteration: 'sharh', meaning: 'Explanation', category: 'Verbs', mnemonic: 'SHARH - Shar explanation' },
  { id: 465, arabic: 'رأي', transliteration: 'ray', meaning: 'Opinion', category: 'Objects', mnemonic: 'RAY - Ray opinion' },
  { id: 466, arabic: 'فكرة', transliteration: 'fikra', meaning: 'Idea', category: 'Objects', mnemonic: 'FIKRA - Fick ra idea' },
  { id: 467, arabic: 'سبب', transliteration: 'sabab', meaning: 'Reason', category: 'Objects', mnemonic: 'SABAB - Sab ab reason' },
  { id: 468, arabic: 'سبب', transliteration: 'sabab', meaning: 'Cause', category: 'Objects', mnemonic: 'SABAB - Sab ab cause' },
  { id: 469, arabic: 'نتيجة', transliteration: 'natija', meaning: 'Result', category: 'Objects', mnemonic: 'NATIJA - Nat ija result' },
  { id: 470, arabic: 'تأثير', transliteration: 'tathir', meaning: 'Influence', category: 'Objects', mnemonic: 'TATHIR - Tat here influence' },
  { id: 471, arabic: 'علاقة', transliteration: 'alaqa', meaning: 'Relationship', category: 'Objects', mnemonic: 'ALAQA - Al aka relationship' },
  { id: 472, arabic: 'فرق', transliteration: 'farq', meaning: 'Difference', category: 'Objects', mnemonic: 'FARQ - Fork difference' },
  { id: 473, arabic: 'يشبه', transliteration: 'yushbih', meaning: 'To resemble', category: 'Verbs', mnemonic: 'YUSHBIH - You shbih resembles' },
  { id: 474, arabic: 'يقارن', transliteration: 'yuqarin', meaning: 'To compare', category: 'Verbs', mnemonic: 'YUQARIN - You car in compares' },
  { id: 475, arabic: 'مثال', transliteration: 'mithal', meaning: 'Example', category: 'Objects', mnemonic: 'MITHAL - Mit hal example' },
  { id: 476, arabic: 'حالة', transliteration: 'hala', meaning: 'Case', category: 'Objects', mnemonic: 'HALA - Hal a case' },
  { id: 477, arabic: 'حالة', transliteration: 'hala', meaning: 'State', category: 'Objects', mnemonic: 'HALA - Hal a state' },
  { id: 478, arabic: 'مظهر', transliteration: 'mazhar', meaning: 'Appearance', category: 'Objects', mnemonic: 'MAZHAR - Maz har appearance' },
  { id: 479, arabic: 'درجة', transliteration: 'daraja', meaning: 'Degree', category: 'Objects', mnemonic: 'DARAJA - Dar aja degree' },
  { id: 480, arabic: 'كمية', transliteration: 'kammiya', meaning: 'Quantity', category: 'Objects', mnemonic: 'KAMMIYA - Cam miya quantity' },
  { id: 481, arabic: 'جودة', transliteration: 'jawda', meaning: 'Quality', category: 'Objects', mnemonic: 'JAWDA - Jow da quality' },
  { id: 482, arabic: 'قيمة', transliteration: 'qima', meaning: 'Value', category: 'Objects', mnemonic: 'QIMA - Kima value' },
  { id: 483, arabic: 'سعر', transliteration: 'sir', meaning: 'Price', category: 'Objects', mnemonic: 'SIR - Sir price' },
  { id: 484, arabic: 'مال', transliteration: 'mal', meaning: 'Money', category: 'Objects', mnemonic: 'MAL - Mall money' },
  { id: 485, arabic: 'دينار', transliteration: 'dinar', meaning: 'Dinar', category: 'Numbers', mnemonic: 'DINAR - Dinar currency' },
  { id: 486, arabic: 'دولار', transliteration: 'dular', meaning: 'Dollar', category: 'Numbers', mnemonic: 'DULAR - Dollar same' },
  { id: 487, arabic: 'راتب', transliteration: 'ratib', meaning: 'Salary', category: 'Objects', mnemonic: 'RATIB - Rat ib salary' },
  { id: 488, arabic: 'ضريبة', transliteration: 'dariba', meaning: 'Tax', category: 'Objects', mnemonic: 'DARIBA - Dar iba tax' },
  { id: 489, arabic: 'توفير', transliteration: 'tawfir', meaning: 'Savings', category: 'Objects', mnemonic: 'TAWFIR - Tow fir savings' },
  { id: 490, arabic: 'دين', transliteration: 'dayn', meaning: 'Debt', category: 'Objects', mnemonic: 'DAYN - Dane debt' },
  { id: 491, arabic: 'مجاني', transliteration: 'majani', meaning: 'Free', category: 'Objects', mnemonic: 'MAJANI - Maj ani free' },
  { id: 492, arabic: 'مدفوع', transliteration: 'madfu', meaning: 'Paid', category: 'Objects', mnemonic: 'MADFU - Mad foo paid' },
  { id: 493, arabic: 'خصم', transliteration: 'khasm', meaning: 'Discount', category: 'Objects', mnemonic: 'KHASM - Has m discount' },
  { id: 494, arabic: 'خدمة', transliteration: 'khidma', meaning: 'Service', category: 'Objects', mnemonic: 'KHIDMA - Kid ma service' },
  { id: 495, arabic: 'هدية', transliteration: 'hadiya', meaning: 'Gift', category: 'Objects', mnemonic: 'HADIYA - Had iya gift' },
  { id: 496, arabic: 'تذكار', transliteration: 'tadhkar', meaning: 'Souvenir', category: 'Objects', mnemonic: 'TADHKAR - Tad car souvenir' },
  { id: 497, arabic: 'ذكرى', transliteration: 'dhikra', meaning: 'Memory', category: 'Objects', mnemonic: 'DHIKRA - Dick ra memory' },
  { id: 498, arabic: 'احتفال', transliteration: 'ihtifal', meaning: 'Celebration', category: 'Greetings', mnemonic: 'IHTIFAL - Itch if al celebration' },
  { id: 499, arabic: 'حفلة', transliteration: 'hafla', meaning: 'Party', category: 'Greetings', mnemonic: 'HAFLA - Haf la party' },
  { id: 500, arabic: 'دعوة', transliteration: 'dawa', meaning: 'Invitation', category: 'Greetings', mnemonic: 'DAWA - Daw a invitation' },
];
