import { Word } from './types';

export const VOCAB_401_500: Word[] = [
  { id: 401, arabic: 'بريد إلكتروني', transliteration: 'barid iliktruniy', meaning: 'Email', category: 'Objects', mnemonic: 'BARID ILIKTRUNIY - Bar id electronic email' },
  { id: 402, arabic: 'إنترنت', transliteration: 'internet', meaning: 'Internet', category: 'Objects', mnemonic: 'INTERNET - Internet same' },
  { id: 403, arabic: 'هاتف محمول', transliteration: 'hatif mahmul', meaning: 'Mobile phone', category: 'Objects', mnemonic: 'HATIF MAHMUL - Hat if mobile' },
  { id: 404, arabic: 'هاتف ذكي', transliteration: 'hatif zaki', meaning: 'Smartphone', category: 'Objects', mnemonic: 'HATIF ZAKI - Hat if smart' },
  { id: 405, arabic: 'رأس', transliteration: 'ra\'s', meaning: 'Head', category: 'People', mnemonic: 'RA\'S - Rass head' },
  { id: 406, arabic: 'وجه', transliteration: 'wajh', meaning: 'Face', category: 'People', mnemonic: 'WAJH - Waj face' },
  { id: 407, arabic: 'عين', transliteration: '\'ain', meaning: 'Eye', category: 'People', mnemonic: '\'AIN - I an eye' },
  { id: 408, arabic: 'أذن', transliteration: 'uzun', meaning: 'Ear', category: 'People', mnemonic: 'UZUN - Ud an ear' },
  { id: 409, arabic: 'أنف', transliteration: 'anf', meaning: 'Nose', category: 'People', mnemonic: 'ANF - An if nose' },
  { id: 410, arabic: 'فم', transliteration: 'fam', meaning: 'Mouth', category: 'People', mnemonic: 'FAM - Fam mouth' },
  { id: 411, arabic: 'سن', transliteration: 'sinn', meaning: 'Tooth', category: 'People', mnemonic: 'SINN - Sin tooth' },
  { id: 412, arabic: 'لسان', transliteration: 'lisan', meaning: 'Tongue', category: 'People', mnemonic: 'LISAN - Lease an tongue' },
  { id: 413, arabic: 'رقبة', transliteration: 'raqabah', meaning: 'Neck', category: 'People', mnemonic: 'RAQABAH - Rack aba neck' },
  { id: 414, arabic: 'كتف', transliteration: 'katif', meaning: 'Shoulder', category: 'People', mnemonic: 'KATIF - Cat if shoulder' },
  { id: 415, arabic: 'ذراع', transliteration: 'zira\'', meaning: 'Arm', category: 'People', mnemonic: 'ZIRA\' - Dear a arm' },
  { id: 416, arabic: 'يد', transliteration: 'yad', meaning: 'Hand', category: 'People', mnemonic: 'YAD - Yad hand' },
  { id: 417, arabic: 'إصبع', transliteration: 'isba\'', meaning: 'Finger', category: 'People', mnemonic: 'ISBA\' - Is ba finger' },
  { id: 418, arabic: 'ظفر', transliteration: 'zufr', meaning: 'Nail', category: 'People', mnemonic: 'ZUFR - Zoo fur nail' },
  { id: 419, arabic: 'صدر', transliteration: 'sadr', meaning: 'Chest', category: 'People', mnemonic: 'SADR - Sad are chest' },
  { id: 420, arabic: 'بطن', transliteration: 'batn', meaning: 'Stomach', category: 'People', mnemonic: 'BATN - Bat an stomach' },
  { id: 421, arabic: 'ظهر', transliteration: 'zahr', meaning: 'Back', category: 'People', mnemonic: 'ZAHR - Zar back' },
  { id: 422, arabic: 'خصر', transliteration: 'khasr', meaning: 'Waist', category: 'People', mnemonic: 'KHASR - Has are waist' },
  { id: 423, arabic: 'رجل', transliteration: 'rijl', meaning: 'Leg', category: 'People', mnemonic: 'RIJL - Rig l leg' },
  { id: 424, arabic: 'ركبة', transliteration: 'rukbah', meaning: 'Knee', category: 'People', mnemonic: 'RUKBAH - Rook ba knee' },
  { id: 425, arabic: 'دم', transliteration: 'dam', meaning: 'Blood', category: 'People', mnemonic: 'DAM - Dam blood' },
  { id: 426, arabic: 'عظم', transliteration: '\'azm', meaning: 'Bone', category: 'People', mnemonic: '\'AZM - As m bone' },
  { id: 427, arabic: 'جلد', transliteration: 'jild', meaning: 'Skin', category: 'People', mnemonic: 'JILD - Jill d skin' },
  { id: 428, arabic: 'شعر', transliteration: 'sya\'r', meaning: 'Hair', category: 'People', mnemonic: 'SYA\'R - Share hair' },
  { id: 429, arabic: 'صوت', transliteration: 'saut', meaning: 'Voice', category: 'People', mnemonic: 'SAUT - Sought voice' },
  { id: 430, arabic: 'صوت', transliteration: 'saut', meaning: 'Sound', category: 'Objects', mnemonic: 'SAUT - Sought sound' },
  { id: 431, arabic: 'رائحة', transliteration: 'raihah', meaning: 'Smell', category: 'Objects', mnemonic: 'RAIHAH - Ray ha smell' },
  { id: 432, arabic: 'طعم', transliteration: 'ta\'m', meaning: 'Taste', category: 'Objects', mnemonic: 'TA\'M - Tam taste' },
  { id: 433, arabic: 'شعور', transliteration: 'syu\'ur', meaning: 'Feeling', category: 'People', mnemonic: 'SYU\'UR - Sure feeling' },
  { id: 434, arabic: 'مزاج', transliteration: 'mizaj', meaning: 'Mood', category: 'People', mnemonic: 'MIZAJ - Miz aj mood' },
  { id: 435, arabic: 'حلم', transliteration: 'hulm', meaning: 'Dream', category: 'People', mnemonic: 'HULM - Helm dream' },
  { id: 436, arabic: 'أمل', transliteration: 'amal', meaning: 'Hope', category: 'People', mnemonic: 'AMAL - A mall hope' },
  { id: 437, arabic: 'سعادة', transliteration: 'sa\'adah', meaning: 'Happiness', category: 'People', mnemonic: 'SA\'ADAH - Sad a happiness' },
  { id: 438, arabic: 'تعاسة', transliteration: 'ta\'asah', meaning: 'Misfortune', category: 'People', mnemonic: 'TA\'ASAH - Toss a misfortune' },
  { id: 439, arabic: 'نجاح', transliteration: 'najah', meaning: 'Success', category: 'Verbs', mnemonic: 'NAJAH - Naj ah success' },
  { id: 440, arabic: 'فشل', transliteration: 'fasyal', meaning: 'Failure', category: 'Verbs', mnemonic: 'FASYAL - Fash al failure' },
  { id: 441, arabic: 'جهد', transliteration: 'juhd', meaning: 'Effort', category: 'Verbs', mnemonic: 'JUHD - Jude effort' },
  { id: 442, arabic: 'خبرة', transliteration: 'khibrah', meaning: 'Experience', category: 'Verbs', mnemonic: 'KHIBRAH - Kib ra experience' },
  { id: 443, arabic: 'معرفة', transliteration: 'ma\'rifah', meaning: 'Knowledge', category: 'Verbs', mnemonic: 'MA\'RIFAH - Mar ifa knowledge' },
  { id: 444, arabic: 'تقنية', transliteration: 'tiqniyah', meaning: 'Technology', category: 'Verbs', mnemonic: 'TIQNIYAH - Tick niya technology' },
  { id: 445, arabic: 'علم', transliteration: '\'ilm', meaning: 'Science', category: 'Objects', mnemonic: '\'ILM - Ill m science' },
  { id: 446, arabic: 'تاريخ', transliteration: 'tarikh', meaning: 'History', category: 'Objects', mnemonic: 'TARIKH - Tar ick history' },
  { id: 447, arabic: 'ثقافة', transliteration: 'thaqafah', meaning: 'Culture', category: 'Objects', mnemonic: 'THAQAFAH - Tack afa culture' },
  { id: 448, arabic: 'تقليد', transliteration: 'taqlid', meaning: 'Tradition', category: 'Objects', mnemonic: 'TAQLID - Tack lid tradition' },
  { id: 449, arabic: 'عادة', transliteration: '\'adah', meaning: 'Habit', category: 'Objects', mnemonic: '\'ADAH - Add a habit' },
  { id: 450, arabic: 'قاعدة', transliteration: 'qa\'idah', meaning: 'Rule', category: 'Objects', mnemonic: 'QA\'IDAH - Caid a rule' },
  { id: 451, arabic: 'قانون', transliteration: 'qanun', meaning: 'Law', category: 'Objects', mnemonic: 'QANUN - Can noon law' },
  { id: 452, arabic: 'حق', transliteration: 'haqq', meaning: 'Right', category: 'Objects', mnemonic: 'HAQQ - Hack right' },
  { id: 453, arabic: 'واجب', transliteration: 'wajib', meaning: 'Duty', category: 'Objects', mnemonic: 'WAJIB - Waj ib duty' },
  { id: 454, arabic: 'مسؤولية', transliteration: 'masuliya', meaning: 'Responsibility', category: 'Objects', mnemonic: 'MASULIYA - Mass ool responsibility' },
  { id: 455, arabic: 'حرية', transliteration: 'hurriya', meaning: 'Freedom', category: 'Objects', mnemonic: 'HURRIYA - Hurry ya freedom' },
  { id: 456, arabic: 'مساواة', transliteration: 'musawa', meaning: 'Equality', category: 'Objects', mnemonic: 'MUSAWA - Moo saw equality' },
  { id: 457, arabic: 'عدالة', transliteration: 'adala', meaning: 'Justice', category: 'Objects', mnemonic: 'ADALA - Add ala justice' },
  { id: 458, arabic: 'حقيقة', transliteration: 'haqiqa', meaning: 'Truth', category: 'Objects', mnemonic: 'HAQIQA - Hack ika truth' },
  { id: 459, arabic: 'كذب', transliteration: 'kadhib', meaning: 'Lie', category: 'Objects', mnemonic: 'KADHIB - Cad hib lie' },
  { id: 460, arabic: 'سر', transliteration: 'sirr', meaning: 'Secret', category: 'Objects', mnemonic: 'SIRR - Sir secret' },
  { id: 461, arabic: 'مشكلة', transliteration: 'musykilah', meaning: 'Problem', category: 'Objects', mnemonic: 'MUSYKILAH - Mush kill a problem' },
  { id: 462, arabic: 'جواب', transliteration: 'jawab', meaning: 'Answer', category: 'Objects', mnemonic: 'JAWAB - Jaw ab answer' },
  { id: 463, arabic: 'سؤال', transliteration: 'su\'al', meaning: 'Question', category: 'Objects', mnemonic: 'SU\'AL - Sue al question' },
  { id: 464, arabic: 'شرح', transliteration: 'syarh', meaning: 'Explanation', category: 'Verbs', mnemonic: 'SYARH - Shar explanation' },
  { id: 465, arabic: 'رأي', transliteration: 'ra\'y', meaning: 'Opinion', category: 'Objects', mnemonic: 'RA\'Y - Ray opinion' },
  { id: 466, arabic: 'فكرة', transliteration: 'fikrah', meaning: 'Idea', category: 'Objects', mnemonic: 'FIKRAH - Fick ra idea' },
  { id: 467, arabic: 'سبب', transliteration: 'sabab', meaning: 'Reason', category: 'Objects', mnemonic: 'SABAB - Sab ab reason' },
  { id: 468, arabic: 'سبب', transliteration: 'sabab', meaning: 'Cause', category: 'Objects', mnemonic: 'SABAB - Sab ab cause' },
  { id: 469, arabic: 'نتيجة', transliteration: 'natijah', meaning: 'Result', category: 'Objects', mnemonic: 'NATIJAH - Nat ija result' },
  { id: 470, arabic: 'تأثير', transliteration: 'ta\'thir', meaning: 'Influence', category: 'Objects', mnemonic: 'TA\'THIR - Tat here influence' },
  { id: 471, arabic: 'علاقة', transliteration: '\'alaqah', meaning: 'Relationship', category: 'Objects', mnemonic: '\'ALAQAH - Al aka relationship' },
  { id: 472, arabic: 'فرق', transliteration: 'farq', meaning: 'Difference', category: 'Objects', mnemonic: 'FARQ - Fork difference' },
  { id: 473, arabic: 'يشبه', transliteration: 'yusybih', meaning: 'To resemble', category: 'Verbs', mnemonic: 'YUSYBIH - You shbih resembles' },
  { id: 474, arabic: 'يقارن', transliteration: 'yuqarin', meaning: 'To compare', category: 'Verbs', mnemonic: 'YUQARIN - You car in compares' },
  { id: 475, arabic: 'مثال', transliteration: 'mithal', meaning: 'Example', category: 'Objects', mnemonic: 'MITHAL - Mit hal example' },
  { id: 476, arabic: 'حالة', transliteration: 'halah', meaning: 'Case', category: 'Objects', mnemonic: 'HALAH - Hal a case' },
  { id: 477, arabic: 'حالة', transliteration: 'halah', meaning: 'State', category: 'Objects', mnemonic: 'HALAH - Hal a state' },
  { id: 478, arabic: 'مظهر', transliteration: 'mazhar', meaning: 'Appearance', category: 'Objects', mnemonic: 'MAZHAR - Maz har appearance' },
  { id: 479, arabic: 'درجة', transliteration: 'darajah', meaning: 'Degree', category: 'Objects', mnemonic: 'DARAJAH - Dar aja degree' },
  { id: 480, arabic: 'كمية', transliteration: 'kammiyah', meaning: 'Quantity', category: 'Objects', mnemonic: 'KAMMIYAH - Cam miya quantity' },
  { id: 481, arabic: 'جودة', transliteration: 'jaudah', meaning: 'Quality', category: 'Objects', mnemonic: 'JAUDAH - Jow da quality' },
  { id: 482, arabic: 'قيمة', transliteration: 'qimah', meaning: 'Value', category: 'Objects', mnemonic: 'QIMAH - Kima value' },
  { id: 483, arabic: 'سعر', transliteration: 'si\'r', meaning: 'Price', category: 'Objects', mnemonic: 'SI\'R - Sir price' },
  { id: 484, arabic: 'مال', transliteration: 'mal', meaning: 'Money', category: 'Objects', mnemonic: 'MAL - Mall money' },
  { id: 485, arabic: 'دينار', transliteration: 'dinar', meaning: 'Dinar', category: 'Numbers', mnemonic: 'DINAR - Dinar currency' },
  { id: 486, arabic: 'دولار', transliteration: 'dular', meaning: 'Dollar', category: 'Numbers', mnemonic: 'DULAR - Dollar same' },
  { id: 487, arabic: 'راتب', transliteration: 'ratib', meaning: 'Salary', category: 'Objects', mnemonic: 'RATIB - Rat ib salary' },
  { id: 488, arabic: 'ضريبة', transliteration: 'daribah', meaning: 'Tax', category: 'Objects', mnemonic: 'DARIBAH - Dar iba tax' },
  { id: 489, arabic: 'توفير', transliteration: 'taufir', meaning: 'Savings', category: 'Objects', mnemonic: 'TAUFIR - Tow fir savings' },
  { id: 490, arabic: 'دين', transliteration: 'dain', meaning: 'Debt', category: 'Objects', mnemonic: 'DAIN - Dane debt' },
  { id: 491, arabic: 'مجاني', transliteration: 'majani', meaning: 'Free', category: 'Objects', mnemonic: 'MAJANI - Maj ani free' },
  { id: 492, arabic: 'مدفوع', transliteration: 'madfu\'', meaning: 'Paid', category: 'Objects', mnemonic: 'MADFU\' - Mad foo paid' },
  { id: 493, arabic: 'خصم', transliteration: 'khasm', meaning: 'Discount', category: 'Objects', mnemonic: 'KHASM - Has m discount' },
  { id: 494, arabic: 'خدمة', transliteration: 'khidmah', meaning: 'Service', category: 'Objects', mnemonic: 'KHIDMAH - Kid ma service' },
  { id: 495, arabic: 'هدية', transliteration: 'hadiyah', meaning: 'Gift', category: 'Objects', mnemonic: 'HADIYAH - Had iya gift' },
  { id: 496, arabic: 'تذكار', transliteration: 'tazkar', meaning: 'Souvenir', category: 'Objects', mnemonic: 'TAZKAR - Tad car souvenir' },
  { id: 497, arabic: 'ذكرى', transliteration: 'zikra', meaning: 'Memory', category: 'Objects', mnemonic: 'ZIKRA - Dick ra memory' },
  { id: 498, arabic: 'احتفال', transliteration: 'ihtifal', meaning: 'Celebration', category: 'Greetings', mnemonic: 'IHTIFAL - Itch if al celebration' },
  { id: 499, arabic: 'حفلة', transliteration: 'haflah', meaning: 'Party', category: 'Greetings', mnemonic: 'HAFLAH - Haf la party' },
  { id: 500, arabic: 'دعوة', transliteration: 'da\'wah', meaning: 'Invitation', category: 'Greetings', mnemonic: 'DA\'WAH - Daw a invitation' },
];
