import { Word } from './types';

export const VOCAB_301_400: Word[] = [
  { id: 301, arabic: 'ماهر', transliteration: 'mahir', meaning: 'Skillful', category: 'Adjectives', mnemonic: 'MAHIR - Ma here skillful' },
  { id: 302, arabic: 'سيء', transliteration: 'sayyi\'', meaning: 'Bad at', category: 'Adjectives', mnemonic: 'SAYYI\' - Say yee bad' },
  { id: 303, arabic: 'فوق', transliteration: 'fauq', meaning: 'Above', category: 'Objects', mnemonic: 'FAUQ - Fork above' },
  { id: 304, arabic: 'تحت', transliteration: 'taht', meaning: 'Below', category: 'Objects', mnemonic: 'TAHT - Taught below' },
  { id: 305, arabic: 'أمام', transliteration: 'amam', meaning: 'Front', category: 'Objects', mnemonic: 'AMAM - A mam in front' },
  { id: 306, arabic: 'خلف', transliteration: 'khalf', meaning: 'Behind', category: 'Objects', mnemonic: 'KHALF - Calf behind' },
  { id: 307, arabic: 'يسار', transliteration: 'yasar', meaning: 'Left', category: 'Objects', mnemonic: 'YASAR - Yes, are left' },
  { id: 308, arabic: 'يمين', transliteration: 'yamin', meaning: 'Right', category: 'Objects', mnemonic: 'YAMIN - Yam in right' },
  { id: 309, arabic: 'داخل', transliteration: 'dakhil', meaning: 'Inside', category: 'Objects', mnemonic: 'DAKHIL - Duck hill inside' },
  { id: 310, arabic: 'خارج', transliteration: 'kharij', meaning: 'Outside', category: 'Objects', mnemonic: 'KHARIJ - Car edge outside' },
  { id: 311, arabic: 'جانب', transliteration: 'janib', meaning: 'Next to', category: 'Objects', mnemonic: 'JANIB - Jan nib next to' },
  { id: 312, arabic: 'هناك', transliteration: 'hunak', meaning: 'There', category: 'Objects', mnemonic: 'HUNAK - Hoo nak there' },
  { id: 313, arabic: 'هنا', transliteration: 'huna', meaning: 'Here', category: 'Objects', mnemonic: 'HUNA - Hoo na here' },
  { id: 314, arabic: 'هذا', transliteration: 'haza', meaning: 'This', category: 'Objects', mnemonic: 'HAZA - Had a this' },
  { id: 315, arabic: 'ذلك', transliteration: 'zalik', meaning: 'That', category: 'Objects', mnemonic: 'ZALIK - Da lick that' },
  { id: 316, arabic: 'أين', transliteration: 'aina', meaning: 'Where', category: 'Objects', mnemonic: 'AINA - I na where' },
  { id: 317, arabic: 'مكان', transliteration: 'makan', meaning: 'Place', category: 'Objects', mnemonic: 'MAKAN - Ma can place' },
  { id: 318, arabic: 'زمن', transliteration: 'zaman', meaning: 'Time', category: 'Time', mnemonic: 'ZAMAN - Zaman is time' },
  { id: 319, arabic: 'ماذا', transliteration: 'maza', meaning: 'What', category: 'Objects', mnemonic: 'MAZA - Mad a what' },
  { id: 320, arabic: 'متى', transliteration: 'mata', meaning: 'When', category: 'Time', mnemonic: 'MATA - Mat a when' },
  { id: 321, arabic: 'من', transliteration: 'man', meaning: 'Who', category: 'People', mnemonic: 'MAN - Man who' },
  { id: 322, arabic: 'لماذا', transliteration: 'limaza', meaning: 'Why', category: 'Objects', mnemonic: 'LIMAZA - Lima da why' },
  { id: 323, arabic: 'كيف', transliteration: 'kaifa', meaning: 'How', category: 'Objects', mnemonic: 'KAIFA - Kayfa how' },
  { id: 324, arabic: 'كم', transliteration: 'kam', meaning: 'How much', category: 'Numbers', mnemonic: 'KAM - Cam how much' },
  { id: 325, arabic: 'لون', transliteration: 'laun', meaning: 'Color', category: 'Objects', mnemonic: 'LAUN - Lawn color' },
  { id: 326, arabic: 'شكل', transliteration: 'syakl', meaning: 'Shape', category: 'Objects', mnemonic: 'SYAKL - Shackle shape' },
  { id: 327, arabic: 'حجم', transliteration: 'hajm', meaning: 'Size', category: 'Objects', mnemonic: 'HAJM - Hajm size' },
  { id: 328, arabic: 'عدد', transliteration: '\'adad', meaning: 'Number', category: 'Numbers', mnemonic: '\'ADAD - Add number' },
  { id: 329, arabic: 'اسم', transliteration: 'ism', meaning: 'Name', category: 'People', mnemonic: 'ISM - Is m name' },
  { id: 330, arabic: 'عنوان', transliteration: '\'unwan', meaning: 'Address', category: 'Objects', mnemonic: '\'UNWAN - Un wan address' },
  { id: 331, arabic: 'رقم', transliteration: 'raqm', meaning: 'Number', category: 'Numbers', mnemonic: 'RAQM - Rack m number' },
  { id: 332, arabic: 'عمر', transliteration: '\'umr', meaning: 'Age', category: 'People', mnemonic: '\'UMR - Um are age' },
  { id: 333, arabic: 'عيد ميلاد', transliteration: '\'id milad', meaning: 'Birthday', category: 'Time', mnemonic: '\'ID MILAD - Id my lad birthday' },
  { id: 334, arabic: 'دولة', transliteration: 'daulah', meaning: 'Country', category: 'Objects', mnemonic: 'DAULAH - Doll a country' },
  { id: 335, arabic: 'مدينة', transliteration: 'madinah', meaning: 'City', category: 'Objects', mnemonic: 'MADINAH - Medina city' },
  { id: 336, arabic: 'قرية', transliteration: 'qaryah', meaning: 'Village', category: 'Objects', mnemonic: 'QARYAH - Car ya village' },
  { id: 337, arabic: 'طريق', transliteration: 'tariq', meaning: 'Road', category: 'Objects', mnemonic: 'TARIQ - Tar ick road' },
  { id: 338, arabic: 'جسر', transliteration: 'jisr', meaning: 'Bridge', category: 'Objects', mnemonic: 'JISR - Jis are bridge' },
  { id: 339, arabic: 'مبنى', transliteration: 'mabna', meaning: 'Building', category: 'Objects', mnemonic: 'MABNA - Mab na building' },
  { id: 340, arabic: 'حديقة', transliteration: 'hadiqah', meaning: 'Park', category: 'Objects', mnemonic: 'HADIQAH - Had ika park' },
  { id: 341, arabic: 'مكتبة', transliteration: 'maktabah', meaning: 'Library', category: 'Objects', mnemonic: 'MAKTABAH - Mac tab a library' },
  { id: 342, arabic: 'متحف', transliteration: 'mathaf', meaning: 'Museum', category: 'Objects', mnemonic: 'MATHAF - Mat haf museum' },
  { id: 343, arabic: 'معرض', transliteration: 'ma\'rad', meaning: 'Exhibition', category: 'Objects', mnemonic: 'MA\'RAD - Mar ad exhibition' },
  { id: 344, arabic: 'حديقة حيوان', transliteration: 'hadiqah hayawan', meaning: 'Zoo', category: 'Objects', mnemonic: 'HADIQAH HAYAWAN - Had ika hay zoo' },
  { id: 345, arabic: 'حوض سمك', transliteration: 'haud samak', meaning: 'Aquarium', category: 'Objects', mnemonic: 'HAUD SAMAK - Howd sam aquarium' },
  { id: 346, arabic: 'ملاهي', transliteration: 'malahi', meaning: 'Amusement park', category: 'Objects', mnemonic: 'MALAHI - Mal a he amusement' },
  { id: 347, arabic: 'معبد', transliteration: 'ma\'bad', meaning: 'Temple', category: 'Objects', mnemonic: 'MA\'BAD - Ma bad temple' },
  { id: 348, arabic: 'مسجد', transliteration: 'masjid', meaning: 'Mosque', category: 'Objects', mnemonic: 'MASJID - Mas jid mosque' },
  { id: 349, arabic: 'كنيسة', transliteration: 'kanisah', meaning: 'Church', category: 'Objects', mnemonic: 'KANISAH - Can is a church' },
  { id: 350, arabic: 'شركة', transliteration: 'syarikah', meaning: 'Company', category: 'Objects', mnemonic: 'SYARIKAH - Share ika company' },
  { id: 351, arabic: 'مصنع', transliteration: 'masna', meaning: 'Factory', category: 'Objects', mnemonic: 'MASNA - Mas na factory' },
  { id: 352, arabic: 'سوق', transliteration: 'suq', meaning: 'Market', category: 'Objects', mnemonic: 'SUQ - Sook market' },
  { id: 353, arabic: 'سوبر ماركت', transliteration: 'subar market', meaning: 'Supermarket', category: 'Objects', mnemonic: 'SUBAR MARKET - Super market' },
  { id: 354, arabic: 'متجر كبير', transliteration: 'matjar kabir', meaning: 'Department store', category: 'Objects', mnemonic: 'MATJAR KABIR - Mat jar big store' },
  { id: 355, arabic: 'دكان', transliteration: 'dukkan', meaning: 'Shop', category: 'Objects', mnemonic: 'DUKKAN - Duck an shop' },
  { id: 356, arabic: 'بريد', transliteration: 'barid', meaning: 'Post office', category: 'Objects', mnemonic: 'BARID - Bar id post' },
  { id: 357, arabic: 'شرطة', transliteration: 'syurtah', meaning: 'Police', category: 'People', mnemonic: 'SYURTAH - Sure ta police' },
  { id: 358, arabic: 'إطفاء', transliteration: 'itfa\'', meaning: 'Fire department', category: 'People', mnemonic: 'ITFA\' - It fa fire' },
  { id: 359, arabic: 'سفارة', transliteration: 'sifarah', meaning: 'Embassy', category: 'Objects', mnemonic: 'SIFARAH - Sif ara embassy' },
  { id: 360, arabic: 'ملابس', transliteration: 'malabis', meaning: 'Clothes', category: 'Objects', mnemonic: 'MALABIS - Mal a bis clothes' },
  { id: 361, arabic: 'قميص', transliteration: 'qamis', meaning: 'Shirt', category: 'Objects', mnemonic: 'QAMIS - Cam is shirt' },
  { id: 362, arabic: 'بنطلون', transliteration: 'bantalun', meaning: 'Pants', category: 'Objects', mnemonic: 'BANTALUN - Pant a loon pants' },
  { id: 363, arabic: 'تنورة', transliteration: 'tannurah', meaning: 'Skirt', category: 'Objects', mnemonic: 'TANNURAH - Tan nura skirt' },
  { id: 364, arabic: 'فستان', transliteration: 'fustan', meaning: 'Dress', category: 'Objects', mnemonic: 'FUSTAN - Fuss tan dress' },
  { id: 365, arabic: 'معطف', transliteration: 'mi\'taf', meaning: 'Coat', category: 'Objects', mnemonic: 'MI\'TAF - Me taf coat' },
  { id: 366, arabic: 'سترة', transliteration: 'sutrah', meaning: 'Jacket', category: 'Objects', mnemonic: 'SUTRAH - Sutra jacket' },
  { id: 367, arabic: 'كنزة', transliteration: 'kunzah', meaning: 'Sweater', category: 'Objects', mnemonic: 'KUNZAH - Coon za sweater' },
  { id: 368, arabic: 'حذاء', transliteration: 'hiza\'', meaning: 'Shoes', category: 'Objects', mnemonic: 'HIZA\' - He da shoes' },
  { id: 369, arabic: 'جوارب', transliteration: 'jawarib', meaning: 'Socks', category: 'Objects', mnemonic: 'JAWARIB - Jaw a rib socks' },
  { id: 370, arabic: 'قبعة', transliteration: 'qubba\'ah', meaning: 'Hat', category: 'Objects', mnemonic: 'QUBBA\'AH - Cub a hat' },
  { id: 371, arabic: 'قفازات', transliteration: 'quffazat', meaning: 'Gloves', category: 'Objects', mnemonic: 'QUFFAZAT - Cuff a zat gloves' },
  { id: 372, arabic: 'نظارات', transliteration: 'nazzarat', meaning: 'Glasses', category: 'Objects', mnemonic: 'NAZZARAT - Naz a rat glasses' },
  { id: 373, arabic: 'ساعة يد', transliteration: 'sa\'ah yad', meaning: 'Watch', category: 'Objects', mnemonic: 'SA\'AH YAD - Saw yad watch' },
  { id: 374, arabic: 'خاتم', transliteration: 'khatim', meaning: 'Ring', category: 'Objects', mnemonic: 'KHATIM - Cat im ring' },
  { id: 375, arabic: 'عقد', transliteration: '\'iqd', meaning: 'Necklace', category: 'Objects', mnemonic: '\'IQD - Ick d necklace' },
  { id: 376, arabic: 'أقراط', transliteration: 'aqrat', meaning: 'Earrings', category: 'Objects', mnemonic: 'AQRAT - Ack rat earrings' },
  { id: 377, arabic: 'حقيبة', transliteration: 'haqibah', meaning: 'Bag', category: 'Objects', mnemonic: 'HAQIBAH - Hack iba bag' },
  { id: 378, arabic: 'محفظة', transliteration: 'mahfazah', meaning: 'Wallet', category: 'Objects', mnemonic: 'MAHFAZAH - Mah faza wallet' },
  { id: 379, arabic: 'مظلة', transliteration: 'mizallah', meaning: 'Umbrella', category: 'Objects', mnemonic: 'MIZALLAH - Miz alla umbrella' },
  { id: 380, arabic: 'مفتاح', transliteration: 'miftah', meaning: 'Key', category: 'Objects', mnemonic: 'MIFTAH - Mif tah key' },
  { id: 381, arabic: 'قلم', transliteration: 'qalam', meaning: 'Pen', category: 'Objects', mnemonic: 'QALAM - Calm pen' },
  { id: 382, arabic: 'قلم رصاص', transliteration: 'qalam rasas', meaning: 'Pencil', category: 'Objects', mnemonic: 'QALAM RASAS - Calm ras pencil' },
  { id: 383, arabic: 'ممحاة', transliteration: 'mimha\'ah', meaning: 'Eraser', category: 'Objects', mnemonic: 'MIMHA\'AH - Mim ha eraser' },
  { id: 384, arabic: 'ورق', transliteration: 'waraq', meaning: 'Paper', category: 'Objects', mnemonic: 'WARAQ - War ack paper' },
  { id: 385, arabic: 'دفتر', transliteration: 'daftar', meaning: 'Notebook', category: 'Objects', mnemonic: 'DAFTAR - Daft are notebook' },
  { id: 386, arabic: 'قاموس', transliteration: 'qamus', meaning: 'Dictionary', category: 'Objects', mnemonic: 'QAMUS - Cam us dictionary' },
  { id: 387, arabic: 'جريدة', transliteration: 'jaridah', meaning: 'Newspaper', category: 'Objects', mnemonic: 'JARIDAH - Jar ida newspaper' },
  { id: 388, arabic: 'مجلة', transliteration: 'majallah', meaning: 'Magazine', category: 'Objects', mnemonic: 'MAJALLAH - Maj alla magazine' },
  { id: 389, arabic: 'رسالة', transliteration: 'risalah', meaning: 'Letter', category: 'Objects', mnemonic: 'RISALAH - Ris ala letter' },
  { id: 390, arabic: 'طعام', transliteration: 'ta\'am', meaning: 'Food', category: 'Objects', mnemonic: 'TA\'AM - Tam food' },
  { id: 391, arabic: 'شراب', transliteration: 'syarab', meaning: 'Drink', category: 'Objects', mnemonic: 'SYARAB - Shar ab drink' },
  { id: 392, arabic: 'وجبة', transliteration: 'wajbah', meaning: 'Meal', category: 'Objects', mnemonic: 'WAJBAH - Waj ba meal' },
  { id: 393, arabic: 'إفطار', transliteration: 'iftar', meaning: 'Breakfast', category: 'Objects', mnemonic: 'IFTAR - If tar breakfast' },
  { id: 394, arabic: 'غداء', transliteration: 'ghada\'', meaning: 'Lunch', category: 'Objects', mnemonic: 'GHADA\' - Gad a lunch' },
  { id: 395, arabic: 'عشاء', transliteration: 'asya\'', meaning: 'Dinner', category: 'Objects', mnemonic: 'ASYA\' - Ash a dinner' },
  { id: 396, arabic: 'وقت', transliteration: 'waqt', meaning: 'Time', category: 'Time', mnemonic: 'WAQT - Wok t time' },
  { id: 397, arabic: 'ساعة', transliteration: 'sa\'ah', meaning: 'Hour', category: 'Time', mnemonic: 'SA\'AH - Saw hour' },
  { id: 398, arabic: 'دقيقة', transliteration: 'daqiqah', meaning: 'Minute', category: 'Time', mnemonic: 'DAQIQAH - Dak ika minute' },
  { id: 399, arabic: 'ثانية', transliteration: 'thaniyah', meaning: 'Second', category: 'Time', mnemonic: 'THANIYAH - Than iya second' },
  { id: 400, arabic: 'لحظة', transliteration: 'lahzah', meaning: 'Moment', category: 'Time', mnemonic: 'LAHZAH - Lah za moment' },
];
