import { Word } from './types';

export const EXTENDED_VOCABULARY: Word[] = [
  { id: 101, arabic: 'شخص', transliteration: 'shakhs', meaning: 'Person', category: 'People', mnemonic: 'SHUCKS - Shucks, a person!' },
  { id: 102, arabic: 'رجل', transliteration: 'rajul', meaning: 'Man', category: 'People', mnemonic: 'RAJUL - Raj is a man' },
  { id: 103, arabic: 'امرأة', transliteration: 'imraa', meaning: 'Woman', category: 'People', mnemonic: 'IM-RAA - I\'m a woman, raa!' },
  { id: 104, arabic: 'طفل', transliteration: 'tifl', meaning: 'Child', category: 'People', mnemonic: 'TIFF-L - Child has a tiff' },
  { id: 105, arabic: 'أم', transliteration: 'umm', meaning: 'Mother', category: 'People', mnemonic: 'UMM - Umm, mother knows' },
  { id: 106, arabic: 'أب', transliteration: 'ab', meaning: 'Father', category: 'People', mnemonic: 'AB - Ab is father' },
  { id: 107, arabic: 'أخ', transliteration: 'akh', meaning: 'Brother', category: 'People', mnemonic: 'ACK - Ack! Brother!' },
  { id: 108, arabic: 'أخت', transliteration: 'ukht', meaning: 'Sister', category: 'People', mnemonic: 'UCHT - Sister says ucht' },
  { id: 109, arabic: 'ابن', transliteration: 'ibn', meaning: 'Son', category: 'People', mnemonic: 'IBN - Ibn is a son' },
  { id: 110, arabic: 'ابنة', transliteration: 'ibna', meaning: 'Daughter', category: 'People', mnemonic: 'IBNA - Ibna is daughter' },
  { id: 111, arabic: 'وقت', transliteration: 'waqt', meaning: 'Time', category: 'Time', mnemonic: 'WAQT - What time?' },
  { id: 112, arabic: 'صباح', transliteration: 'sabah', meaning: 'Morning', category: 'Time', mnemonic: 'SABAH - Saba in the morning' },
  { id: 113, arabic: 'ظهر', transliteration: 'zuhr', meaning: 'Noon', category: 'Time', mnemonic: 'ZUHR - Zoo at noon' },
  { id: 114, arabic: 'ليل', transliteration: 'layl', meaning: 'Night', category: 'Time', mnemonic: 'LAYL - Lay low at night' },
  { id: 115, arabic: 'أسبوع', transliteration: 'usbu', meaning: 'Week', category: 'Time', mnemonic: 'USBU - Us boo for a week' },
  { id: 116, arabic: 'سنة', transliteration: 'sana', meaning: 'Year', category: 'Time', mnemonic: 'SANA - Sana is a year' },
  { id: 117, arabic: 'ربيع', transliteration: 'rabi', meaning: 'Spring', category: 'Time', mnemonic: 'RABI - Rabbi in spring' },
  { id: 118, arabic: 'صيف', transliteration: 'sayf', meaning: 'Summer', category: 'Time', mnemonic: 'SAYF - Safe in summer' },
  { id: 119, arabic: 'خريف', transliteration: 'kharif', meaning: 'Autumn', category: 'Time', mnemonic: 'KHARIF - Calf in autumn' },
  { id: 120, arabic: 'شتاء', transliteration: 'shita', meaning: 'Winter', category: 'Time', mnemonic: 'SHITA - Shiver in winter' },
  { id: 121, arabic: 'طقس', transliteration: 'taqs', meaning: 'Weather', category: 'Nature', mnemonic: 'TAQS - Tax the weather' },
  { id: 122, arabic: 'مطر', transliteration: 'matar', meaning: 'Rain', category: 'Nature', mnemonic: 'MATAR - Matter of rain' },
  { id: 123, arabic: 'ثلج', transliteration: 'thalj', meaning: 'Snow', category: 'Nature', mnemonic: 'THALJ - Tall snow' },
  { id: 124, arabic: 'ريح', transliteration: 'rih', meaning: 'Wind', category: 'Nature', mnemonic: 'RIH - Reach the wind' },
  { id: 125, arabic: 'سماء', transliteration: 'sama', meaning: 'Sky', category: 'Nature', mnemonic: 'SAMA - Same sky' },
  { id: 126, arabic: 'بحر', transliteration: 'bahr', meaning: 'Sea', category: 'Nature', mnemonic: 'BAHR - Bar by the sea' },
  { id: 127, arabic: 'جبل', transliteration: 'jabal', meaning: 'Mountain', category: 'Nature', mnemonic: 'JABAL - Jabba on mountain' },
  { id: 128, arabic: 'نهر', transliteration: 'nahr', meaning: 'River', category: 'Nature', mnemonic: 'NAHR - Near the river' },
  { id: 129, arabic: 'شجرة', transliteration: 'shajara', meaning: 'Tree', category: 'Nature', mnemonic: 'SHAJARA - Shag a tree' },
  { id: 130, arabic: 'زهرة', transliteration: 'zahra', meaning: 'Flower', category: 'Nature', mnemonic: 'ZAHRA - Zara picks flowers' },
  { id: 131, arabic: 'طائر', transliteration: 'tair', meaning: 'Bird', category: 'Nature', mnemonic: 'TAIR - Tire the bird' },
  { id: 132, arabic: 'سمك', transliteration: 'samak', meaning: 'Fish', category: 'Nature', mnemonic: 'SAMAK - Smack the fish' },
  { id: 133, arabic: 'لحم', transliteration: 'lahm', meaning: 'Meat', category: 'Objects', mnemonic: 'LAHM - Lamb meat' },
  { id: 134, arabic: 'أرز', transliteration: 'aruz', meaning: 'Rice', category: 'Objects', mnemonic: 'ARUZ - A ruse for rice' },
  { id: 135, arabic: 'خبز', transliteration: 'khubz', meaning: 'Bread', category: 'Objects', mnemonic: 'KHUBZ - Clubs eat bread' },
  { id: 136, arabic: 'بيض', transliteration: 'bayd', meaning: 'Egg', category: 'Objects', mnemonic: 'BAYD - Bade egg' },
  { id: 137, arabic: 'خضار', transliteration: 'khudar', meaning: 'Vegetables', category: 'Objects', mnemonic: 'KHUDAR - Could are vegetables' },
  { id: 138, arabic: 'فاكهة', transliteration: 'fakiha', meaning: 'Fruit', category: 'Objects', mnemonic: 'FAKIHA - Fake fruit' },
  { id: 139, arabic: 'شاي', transliteration: 'shay', meaning: 'Tea', category: 'Objects', mnemonic: 'SHAY - Shy tea' },
  { id: 140, arabic: 'قهوة', transliteration: 'qahwa', meaning: 'Coffee', category: 'Objects', mnemonic: 'QAHWA - Cough coffee' },
  { id: 141, arabic: 'حليب', transliteration: 'halib', meaning: 'Milk', category: 'Objects', mnemonic: 'HALIB - Hal sips milk' },
  { id: 142, arabic: 'متجر', transliteration: 'matjar', meaning: 'Shop', category: 'Objects', mnemonic: 'MATJAR - Match jar at shop' },
  { id: 143, arabic: 'مطعم', transliteration: 'matam', meaning: 'Restaurant', category: 'Objects', mnemonic: 'MATAM - Mat at restaurant' },
  { id: 144, arabic: 'بنك', transliteration: 'bank', meaning: 'Bank', category: 'Objects', mnemonic: 'BANK - Bank sounds same' },
  { id: 145, arabic: 'مستشفى', transliteration: 'mustashfa', meaning: 'Hospital', category: 'Objects', mnemonic: 'MUSTASHFA - Must shift to hospital' },
  { id: 146, arabic: 'محطة', transliteration: 'mahatta', meaning: 'Station', category: 'Objects', mnemonic: 'MAHATTA - Ma had a station' },
  { id: 147, arabic: 'مطار', transliteration: 'matar', meaning: 'Airport', category: 'Objects', mnemonic: 'MATAR - Matter at airport' },
  { id: 148, arabic: 'فندق', transliteration: 'funduq', meaning: 'Hotel', category: 'Objects', mnemonic: 'FUNDUQ - Fun duke at hotel' },
  { id: 149, arabic: 'غرفة', transliteration: 'ghurfa', meaning: 'Room', category: 'Objects', mnemonic: 'GHURFA - Giraffe in room' },
  { id: 150, arabic: 'مكتب', transliteration: 'maktab', meaning: 'Desk / Office', category: 'Objects', mnemonic: 'MAKTAB - Mac tab on desk' },
  { id: 151, arabic: 'كرسي', transliteration: 'kursi', meaning: 'Chair', category: 'Objects', mnemonic: 'KURSI - Curse the chair' },
  { id: 152, arabic: 'باب', transliteration: 'bab', meaning: 'Door', category: 'Objects', mnemonic: 'BAB - Bab at the door' },
  { id: 153, arabic: 'نافذة', transliteration: 'nafidha', meaning: 'Window', category: 'Objects', mnemonic: 'NAFIDHA - Naf at window' },
  { id: 154, arabic: 'تلفاز', transliteration: 'tilfaz', meaning: 'Television', category: 'Objects', mnemonic: 'TILFAZ - Tilt the TV' },
  { id: 155, arabic: 'راديو', transliteration: 'radyu', meaning: 'Radio', category: 'Objects', mnemonic: 'RADYU - Radio sounds same' },
  { id: 156, arabic: 'هاتف', transliteration: 'hatif', meaning: 'Telephone', category: 'Objects', mnemonic: 'HATIF - Hat if phone' },
  { id: 157, arabic: 'حاسوب', transliteration: 'hasub', meaning: 'Computer', category: 'Objects', mnemonic: 'HASUB - Has a sub computer' },
  { id: 158, arabic: 'ساعة', transliteration: 'saa', meaning: 'Clock / Watch', category: 'Objects', mnemonic: 'SAA - Saw the clock' },
  { id: 159, arabic: 'كاميرا', transliteration: 'kamira', meaning: 'Camera', category: 'Objects', mnemonic: 'KAMIRA - Camera sounds same' },
  { id: 160, arabic: 'صورة', transliteration: 'sura', meaning: 'Picture', category: 'Objects', mnemonic: 'SURA - Sure a picture' },
  { id: 161, arabic: 'موسيقى', transliteration: 'musiqa', meaning: 'Music', category: 'Objects', mnemonic: 'MUSIQA - Music sounds same' },
  { id: 162, arabic: 'فيلم', transliteration: 'film', meaning: 'Movie / Film', category: 'Objects', mnemonic: 'FILM - Film sounds same' },
  { id: 163, arabic: 'رياضة', transliteration: 'riyada', meaning: 'Sports', category: 'Objects', mnemonic: 'RIYADA - Riyad plays sports' },
  { id: 164, arabic: 'دراسة', transliteration: 'dirasa', meaning: 'Study', category: 'Verbs', mnemonic: 'DIRASA - Dear Asa studies' },
  { id: 165, arabic: 'عمل', transliteration: 'amal', meaning: 'Work', category: 'Verbs', mnemonic: 'AMAL - A mall for work' },
  { id: 166, arabic: 'يلعب', transliteration: 'yalb', meaning: 'To play', category: 'Verbs', mnemonic: 'YALB - Yelp to play' },
  { id: 167, arabic: 'يستريح', transliteration: 'yastarih', meaning: 'To rest', category: 'Verbs', mnemonic: 'YASTARIH - Yes, tar to rest' },
  { id: 168, arabic: 'يعمل', transliteration: 'yamal', meaning: 'To work', category: 'Verbs', mnemonic: 'YAMAL - Yam all work' },
  { id: 169, arabic: 'يعلم', transliteration: 'yualim', meaning: 'To teach', category: 'Verbs', mnemonic: 'YUALIM - You a limb teaches' },
  { id: 170, arabic: 'يتعلم', transliteration: 'yataalm', meaning: 'To learn', category: 'Verbs', mnemonic: 'YATAALM - Yata alms to learn' },
  { id: 171, arabic: 'يبدأ', transliteration: 'yabda', meaning: 'To begin', category: 'Verbs', mnemonic: 'YABDA - Yab da begins' },
  { id: 172, arabic: 'ينتهي', transliteration: 'yantahi', meaning: 'To end', category: 'Verbs', mnemonic: 'YANTAHI - Yanta he ends' },
  { id: 173, arabic: 'ينسى', transliteration: 'yansa', meaning: 'To forget', category: 'Verbs', mnemonic: 'YANSA - Yansa forgets' },
  { id: 174, arabic: 'يتذكر', transliteration: 'yatadhkar', meaning: 'To remember', category: 'Verbs', mnemonic: 'YATADHKAR - Yata car remembers' },
  { id: 175, arabic: 'يفهم', transliteration: 'yafham', meaning: 'To understand', category: 'Verbs', mnemonic: 'YAFHAM - Yaf ham understands' },
  { id: 176, arabic: 'يفكر', transliteration: 'yufakkir', meaning: 'To think', category: 'Verbs', mnemonic: 'YUFAKKIR - You faker thinks' },
  { id: 177, arabic: 'يؤمن', transliteration: 'yumin', meaning: 'To believe', category: 'Verbs', mnemonic: 'YUMIN - You mean to believe' },
  { id: 178, arabic: 'يشعر', transliteration: 'yashur', meaning: 'To feel', category: 'Verbs', mnemonic: 'YASHUR - Yash sure feels' },
  { id: 179, arabic: 'يضحك', transliteration: 'yadhak', meaning: 'To laugh', category: 'Verbs', mnemonic: 'YADHAK - Yad hack laughs' },
  { id: 180, arabic: 'يبكي', transliteration: 'yabki', meaning: 'To cry', category: 'Verbs', mnemonic: 'YABKI - Yab key cries' },
  { id: 181, arabic: 'يغني', transliteration: 'yughanni', meaning: 'To sing', category: 'Verbs', mnemonic: 'YUGHANNI - You ganny sings' },
  { id: 182, arabic: 'يرقص', transliteration: 'yarqus', meaning: 'To dance', category: 'Verbs', mnemonic: 'YARQUS - Yar cuss dances' },
  { id: 183, arabic: 'يلبس', transliteration: 'yalbis', meaning: 'To wear', category: 'Verbs', mnemonic: 'YALBIS - Yal bis wears' },
  { id: 184, arabic: 'يخلع', transliteration: 'yakhla', meaning: 'To take off', category: 'Verbs', mnemonic: 'YAKHLA - Yak la takes off' },
  { id: 185, arabic: 'يغسل', transliteration: 'yaghsil', meaning: 'To wash', category: 'Verbs', mnemonic: 'YAGHSIL - Yag sill washes' },
  { id: 186, arabic: 'ينظف', transliteration: 'yunazif', meaning: 'To clean', category: 'Verbs', mnemonic: 'YUNAZIF - You Nazi cleans' },
  { id: 187, arabic: 'يطبخ', transliteration: 'yatbukh', meaning: 'To cook', category: 'Verbs', mnemonic: 'YATBUKH - Yat book cooks' },
  { id: 188, arabic: 'يقطع', transliteration: 'yaqta', meaning: 'To cut', category: 'Verbs', mnemonic: 'YAQTA - Yak ta cuts' },
  { id: 189, arabic: 'يقرض', transliteration: 'yuqrid', meaning: 'To lend', category: 'Verbs', mnemonic: 'YUQRID - You crid lends' },
  { id: 190, arabic: 'يستعير', transliteration: 'yastaeer', meaning: 'To borrow', category: 'Verbs', mnemonic: 'YASTAEER - Yes, tear borrows' },
  { id: 191, arabic: 'يعطي', transliteration: 'yuti', meaning: 'To give', category: 'Verbs', mnemonic: 'YUTI - You tea gives' },
  { id: 192, arabic: 'يستلم', transliteration: 'yastalim', meaning: 'To receive', category: 'Verbs', mnemonic: 'YASTALIM - Yes, tall receives' },
  { id: 193, arabic: 'يرسل', transliteration: 'yursil', meaning: 'To send', category: 'Verbs', mnemonic: 'YURSIL - Your sill sends' },
  { id: 194, arabic: 'يصل', transliteration: 'yasil', meaning: 'To arrive', category: 'Verbs', mnemonic: 'YASIL - Yes, sill arrives' },
  { id: 195, arabic: 'يبحث', transliteration: 'yabhath', meaning: 'To search', category: 'Verbs', mnemonic: 'YABHATH - Yab hat searches' },
  { id: 196, arabic: 'يجد', transliteration: 'yajid', meaning: 'To find', category: 'Verbs', mnemonic: 'YAJID - Yaj id finds' },
  { id: 197, arabic: 'يختار', transliteration: 'yakhtar', meaning: 'To choose', category: 'Verbs', mnemonic: 'YAKHTAR - Yak tar chooses' },
  { id: 198, arabic: 'يقرر', transliteration: 'yuqarrir', meaning: 'To decide', category: 'Verbs', mnemonic: 'YUQARRIR - You car decides' },
  { id: 199, arabic: 'يغير', transliteration: 'yughayyir', meaning: 'To change', category: 'Verbs', mnemonic: 'YUGHAYYIR - You gayer changes' },
  { id: 200, arabic: 'يصلح', transliteration: 'yuslih', meaning: 'To fix', category: 'Verbs', mnemonic: 'YUSLIH - You sly fixes' },
];
